/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_EXTENSIONS_SUBSTRAIT_EXTENSIONS_EXTENSIONS_PB_H_INCLUDED
#define PB_SUBSTRAIT_EXTENSIONS_SUBSTRAIT_EXTENSIONS_EXTENSIONS_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/any.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct substrait_extensions_Simple_Extension_URI {
    /* A surrogate key used in the context of a single plan used to reference the
 URI associated with an extension. */
    uint32_t extension_uri_anchor;
    /* The URI where this extension YAML can be retrieved. This is the "namespace"
 of this extension. */
    pb_callback_t uri;
} substrait_extensions_Simple_Extension_URI_t;

/* Describes a Type */
typedef struct substrait_extensions_Simple_Extension_Declaration_Extension_Type {
    /* references the extension_uri_anchor defined for a specific extension URI. */
    uint32_t extension_uri_reference;
    /* A surrogate key used in the context of a single plan to reference a
 specific extension type */
    uint32_t type_anchor;
    /* the name of the type in the defined extension YAML. */
    pb_callback_t name;
} substrait_extensions_Simple_Extension_Declaration_Extension_Type_t;

typedef struct substrait_extensions_Simple_Extension_Declaration_Extension_Type_Variation {
    /* references the extension_uri_anchor defined for a specific extension URI. */
    uint32_t extension_uri_reference;
    /* A surrogate key used in the context of a single plan to reference a
 specific type variation */
    uint32_t type_variation_anchor;
    /* the name of the type in the defined extension YAML. */
    pb_callback_t name;
} substrait_extensions_Simple_Extension_Declaration_Extension_Type_Variation_t;

typedef struct substrait_extensions_Simple_Extension_Declaration_Extension_Function {
    /* references the extension_uri_anchor defined for a specific extension URI. */
    uint32_t extension_uri_reference;
    /* A surrogate key used in the context of a single plan to reference a
 specific function */
    uint32_t function_anchor;
    /* A function signature compound name */
    pb_callback_t name;
} substrait_extensions_Simple_Extension_Declaration_Extension_Function_t;

/* Describes a mapping between a specific extension entity and the uri where
 that extension can be found. */
typedef struct substrait_extensions_Simple_Extension_Declaration {
    pb_size_t which_mapping_type;
    union substrait_extensions_Simple_Extension_Declaration_mapping_type {
        substrait_extensions_Simple_Extension_Declaration_Extension_Type_t extension_type;
        substrait_extensions_Simple_Extension_Declaration_Extension_Type_Variation_t extension_type_variation;
        substrait_extensions_Simple_Extension_Declaration_Extension_Function_t extension_function;
    } mapping_type;
} substrait_extensions_Simple_Extension_Declaration_t;

/* A generic object that can be used to embed additional extension information
 into the serialized substrait plan. */
typedef struct substrait_extensions_Advanced_Extension {
    /* An optimization is helpful information that don't influence semantics. May
 be ignored by a consumer. */
    pb_callback_t optimization;
    /* An enhancement alter semantics. Cannot be ignored by a consumer. */
    bool has_enhancement;
    google_protobuf_Any_t enhancement;
} substrait_extensions_Advanced_Extension_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_INIT_DEFAULT {0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_INIT_DEFAULT {0, {SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_INIT_DEFAULT}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_INIT_DEFAULT {0, 0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_INIT_DEFAULT {0, 0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_INIT_DEFAULT {0, 0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_INIT_DEFAULT {{{NULL}, NULL}, false, GOOGLE_PROTOBUF_ANY_INIT_DEFAULT}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_INIT_ZERO {0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_INIT_ZERO {0, {SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_INIT_ZERO}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_INIT_ZERO {0, 0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_INIT_ZERO {0, 0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_INIT_ZERO {0, 0, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_INIT_ZERO {{{NULL}, NULL}, false, GOOGLE_PROTOBUF_ANY_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_EXTENSION_URI_ANCHOR_TAG 1
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_URI_TAG 2
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_EXTENSION_URI_REFERENCE_TAG 1
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_TYPE_ANCHOR_TAG 2
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_NAME_TAG 3
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_EXTENSION_URI_REFERENCE_TAG 1
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_TYPE_VARIATION_ANCHOR_TAG 2
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_NAME_TAG 3
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_EXTENSION_URI_REFERENCE_TAG 1
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_FUNCTION_ANCHOR_TAG 2
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_NAME_TAG 3
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_TAG 1
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_TAG 2
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_TAG 3
#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_OPTIMIZATION_TAG 1
#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_ENHANCEMENT_TAG 2

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   extension_uri_anchor,   1) \
X(a, CALLBACK, SINGULAR, STRING,   uri,               2)
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_CALLBACK pb_default_field_callback
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_DEFAULT NULL

#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mapping_type,extension_type,mapping_type.extension_type),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mapping_type,extension_type_variation,mapping_type.extension_type_variation),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mapping_type,extension_function,mapping_type.extension_function),   3)
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_CALLBACK NULL
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_DEFAULT NULL
#define substrait_extensions_Simple_Extension_Declaration_t_mapping_type_extension_type_MSGTYPE substrait_extensions_Simple_Extension_Declaration_Extension_Type_t
#define substrait_extensions_Simple_Extension_Declaration_t_mapping_type_extension_type_variation_MSGTYPE substrait_extensions_Simple_Extension_Declaration_Extension_Type_Variation_t
#define substrait_extensions_Simple_Extension_Declaration_t_mapping_type_extension_function_MSGTYPE substrait_extensions_Simple_Extension_Declaration_Extension_Function_t

#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   extension_uri_reference,   1) \
X(a, STATIC,   SINGULAR, UINT32,   type_anchor,       2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3)
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_CALLBACK pb_default_field_callback
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_DEFAULT NULL

#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   extension_uri_reference,   1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_anchor,   2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3)
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_DEFAULT NULL

#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   extension_uri_reference,   1) \
X(a, STATIC,   SINGULAR, UINT32,   function_anchor,   2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3)
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_DEFAULT NULL

#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  optimization,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enhancement,       2)
#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_DEFAULT NULL
#define substrait_extensions_Advanced_Extension_t_optimization_MSGTYPE google_protobuf_Any_t
#define substrait_extensions_Advanced_Extension_t_enhancement_MSGTYPE google_protobuf_Any_t

extern const pb_msgdesc_t substrait_extensions_Simple_Extension_URI_t_msg;
extern const pb_msgdesc_t substrait_extensions_Simple_Extension_Declaration_t_msg;
extern const pb_msgdesc_t substrait_extensions_Simple_Extension_Declaration_Extension_Type_t_msg;
extern const pb_msgdesc_t substrait_extensions_Simple_Extension_Declaration_Extension_Type_Variation_t_msg;
extern const pb_msgdesc_t substrait_extensions_Simple_Extension_Declaration_Extension_Function_t_msg;
extern const pb_msgdesc_t substrait_extensions_Advanced_Extension_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI_FIELDS &substrait_extensions_Simple_Extension_URI_t_msg
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_FIELDS &substrait_extensions_Simple_Extension_Declaration_t_msg
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_FIELDS &substrait_extensions_Simple_Extension_Declaration_Extension_Type_t_msg
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION_FIELDS &substrait_extensions_Simple_Extension_Declaration_Extension_Type_Variation_t_msg
#define SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION_FIELDS &substrait_extensions_Simple_Extension_Declaration_Extension_Function_t_msg
#define SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_FIELDS &substrait_extensions_Advanced_Extension_t_msg

/* Maximum encoded size of messages (where known) */
/* substrait_extensions_SimpleExtensionURI_size depends on runtime parameters */
/* substrait_extensions_SimpleExtensionDeclaration_size depends on runtime parameters */
/* substrait_extensions_SimpleExtensionDeclaration_ExtensionType_size depends on runtime parameters */
/* substrait_extensions_SimpleExtensionDeclaration_ExtensionTypeVariation_size depends on runtime parameters */
/* substrait_extensions_SimpleExtensionDeclaration_ExtensionFunction_size depends on runtime parameters */
/* substrait_extensions_AdvancedExtension_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
