/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "substrait/extensions/extensions.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_URI, substrait_extensions_Simple_Extension_URI_t, AUTO)


PB_BIND(SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION, substrait_extensions_Simple_Extension_Declaration_t, AUTO)


PB_BIND(SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE, substrait_extensions_Simple_Extension_Declaration_Extension_Type_t, AUTO)


PB_BIND(SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_TYPE_VARIATION, substrait_extensions_Simple_Extension_Declaration_Extension_Type_Variation_t, AUTO)


PB_BIND(SUBSTRAIT_EXTENSIONS_SIMPLE_EXTENSION_DECLARATION_EXTENSION_FUNCTION, substrait_extensions_Simple_Extension_Declaration_Extension_Function_t, AUTO)


PB_BIND(SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION, substrait_extensions_Advanced_Extension_t, AUTO)



