/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "google/protobuf/empty.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GOOGLE_PROTOBUF_EMPTY, google_protobuf_Empty_t, AUTO)



