/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "substrait/algebra.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SUBSTRAIT_REL_COMMON, substrait_Rel_Common_t, 2)


PB_BIND(SUBSTRAIT_REL_COMMON_DIRECT, substrait_Rel_Common_Direct_t, AUTO)


PB_BIND(SUBSTRAIT_REL_COMMON_EMIT, substrait_Rel_Common_Emit_t, AUTO)


PB_BIND(SUBSTRAIT_REL_COMMON_HINT, substrait_Rel_Common_Hint_t, 2)


PB_BIND(SUBSTRAIT_REL_COMMON_HINT_STATS, substrait_Rel_Common_Hint_Stats_t, AUTO)


PB_BIND(SUBSTRAIT_REL_COMMON_HINT_RUNTIME_CONSTRAINT, substrait_Rel_Common_Hint_Runtime_Constraint_t, AUTO)


PB_BIND(SUBSTRAIT_REL_COMMON_HINT_SAVED_COMPUTATION, substrait_Rel_Common_Hint_Saved_Computation_t, AUTO)


PB_BIND(SUBSTRAIT_REL_COMMON_HINT_LOADED_COMPUTATION, substrait_Rel_Common_Hint_Loaded_Computation_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL, substrait_Read_Rel_t, 2)


PB_BIND(SUBSTRAIT_READ_REL_NAMED_TABLE, substrait_Read_Rel_Named_Table_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_ICEBERG_TABLE, substrait_Read_Rel_Iceberg_Table_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_ICEBERG_TABLE_METADATA_FILE_READ, substrait_Read_Rel_Iceberg_Table_Metadata_File_Read_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_VIRTUAL_TABLE, substrait_Read_Rel_Virtual_Table_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_EXTENSION_TABLE, substrait_Read_Rel_Extension_Table_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_LOCAL_FILES, substrait_Read_Rel_Local_Files_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_LOCAL_FILES_FILE_OR_FILES, substrait_Read_Rel_Local_Files_File_Or_Files_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_LOCAL_FILES_FILE_OR_FILES_PARQUET_READ_OPTIONS, substrait_Read_Rel_Local_Files_File_Or_Files_Parquet_Read_Options_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_LOCAL_FILES_FILE_OR_FILES_ARROW_READ_OPTIONS, substrait_Read_Rel_Local_Files_File_Or_Files_Arrow_Read_Options_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_LOCAL_FILES_FILE_OR_FILES_ORC_READ_OPTIONS, substrait_Read_Rel_Local_Files_File_Or_Files_Orc_Read_Options_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_LOCAL_FILES_FILE_OR_FILES_DWRF_READ_OPTIONS, substrait_Read_Rel_Local_Files_File_Or_Files_Dwrf_Read_Options_t, AUTO)


PB_BIND(SUBSTRAIT_READ_REL_LOCAL_FILES_FILE_OR_FILES_DELIMITER_SEPARATED_TEXT_READ_OPTIONS, substrait_Read_Rel_Local_Files_File_Or_Files_Delimiter_Separated_Text_Read_Options_t, AUTO)


PB_BIND(SUBSTRAIT_PROJECT_REL, substrait_Project_Rel_t, 2)


PB_BIND(SUBSTRAIT_JOIN_REL, substrait_Join_Rel_t, 2)


PB_BIND(SUBSTRAIT_CROSS_REL, substrait_Cross_Rel_t, 2)


PB_BIND(SUBSTRAIT_FETCH_REL, substrait_Fetch_Rel_t, 2)


PB_BIND(SUBSTRAIT_AGGREGATE_REL, substrait_Aggregate_Rel_t, 2)


PB_BIND(SUBSTRAIT_AGGREGATE_REL_GROUPING, substrait_Aggregate_Rel_Grouping_t, AUTO)


PB_BIND(SUBSTRAIT_AGGREGATE_REL_MEASURE, substrait_Aggregate_Rel_Measure_t, 2)


PB_BIND(SUBSTRAIT_CONSISTENT_PARTITION_WINDOW_REL, substrait_Consistent_Partition_Window_Rel_t, 2)


PB_BIND(SUBSTRAIT_CONSISTENT_PARTITION_WINDOW_REL_WINDOW_REL_FUNCTION, substrait_Consistent_Partition_Window_Rel_Window_Rel_Function_t, AUTO)


PB_BIND(SUBSTRAIT_SORT_REL, substrait_Sort_Rel_t, 2)


PB_BIND(SUBSTRAIT_FILTER_REL, substrait_Filter_Rel_t, 2)


PB_BIND(SUBSTRAIT_SET_REL, substrait_Set_Rel_t, 2)


PB_BIND(SUBSTRAIT_EXTENSION_SINGLE_REL, substrait_Extension_Single_Rel_t, 2)


PB_BIND(SUBSTRAIT_EXTENSION_LEAF_REL, substrait_Extension_Leaf_Rel_t, 2)


PB_BIND(SUBSTRAIT_EXTENSION_MULTI_REL, substrait_Extension_Multi_Rel_t, 2)


PB_BIND(SUBSTRAIT_EXCHANGE_REL, substrait_Exchange_Rel_t, 2)


PB_BIND(SUBSTRAIT_EXCHANGE_REL_SCATTER_FIELDS, substrait_Exchange_Rel_Scatter_Fields_t, AUTO)


PB_BIND(SUBSTRAIT_EXCHANGE_REL_SINGLE_BUCKET_EXPRESSION, substrait_Exchange_Rel_Single_Bucket_Expression_t, 2)


PB_BIND(SUBSTRAIT_EXCHANGE_REL_MULTI_BUCKET_EXPRESSION, substrait_Exchange_Rel_Multi_Bucket_Expression_t, 2)


PB_BIND(SUBSTRAIT_EXCHANGE_REL_BROADCAST, substrait_Exchange_Rel_Broadcast_t, AUTO)


PB_BIND(SUBSTRAIT_EXCHANGE_REL_ROUND_ROBIN, substrait_Exchange_Rel_Round_Robin_t, AUTO)


PB_BIND(SUBSTRAIT_EXCHANGE_REL_EXCHANGE_TARGET, substrait_Exchange_Rel_Exchange_Target_t, AUTO)


PB_BIND(SUBSTRAIT_EXPAND_REL, substrait_Expand_Rel_t, 2)


PB_BIND(SUBSTRAIT_EXPAND_REL_EXPAND_FIELD, substrait_Expand_Rel_Expand_Field_t, 2)


PB_BIND(SUBSTRAIT_EXPAND_REL_SWITCHING_FIELD, substrait_Expand_Rel_Switching_Field_t, AUTO)


PB_BIND(SUBSTRAIT_REL_ROOT, substrait_Rel_Root_t, AUTO)


PB_BIND(SUBSTRAIT_REL, substrait_Rel_t, AUTO)


PB_BIND(SUBSTRAIT_NAMED_OBJECT_WRITE, substrait_Named_Object_Write_t, AUTO)


PB_BIND(SUBSTRAIT_EXTENSION_OBJECT, substrait_Extension_Object_t, AUTO)


PB_BIND(SUBSTRAIT_DDL_REL, substrait_Ddl_Rel_t, 2)


PB_BIND(SUBSTRAIT_WRITE_REL, substrait_Write_Rel_t, 2)


PB_BIND(SUBSTRAIT_UPDATE_REL, substrait_Update_Rel_t, 2)


PB_BIND(SUBSTRAIT_UPDATE_REL_TRANSFORM_EXPRESSION, substrait_Update_Rel_Transform_Expression_t, 2)


PB_BIND(SUBSTRAIT_NAMED_TABLE, substrait_Named_Table_t, AUTO)


PB_BIND(SUBSTRAIT_COMPARISON_JOIN_KEY, substrait_Comparison_Join_Key_t, AUTO)


PB_BIND(SUBSTRAIT_COMPARISON_JOIN_KEY_COMPARISON_TYPE, substrait_Comparison_Join_Key_Comparison_Type_t, AUTO)


PB_BIND(SUBSTRAIT_HASH_JOIN_REL, substrait_Hash_Join_Rel_t, 2)


PB_BIND(SUBSTRAIT_MERGE_JOIN_REL, substrait_Merge_Join_Rel_t, 2)


PB_BIND(SUBSTRAIT_NESTED_LOOP_JOIN_REL, substrait_Nested_Loop_Join_Rel_t, 2)


PB_BIND(SUBSTRAIT_FUNCTION_ARGUMENT, substrait_Function_Argument_t, 2)


PB_BIND(SUBSTRAIT_FUNCTION_OPTION, substrait_Function_Option_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION, substrait_Expression_t, 2)


PB_BIND(SUBSTRAIT_EXPRESSION_ENUM, substrait_Expression_Enum_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_ENUM_EMPTY, substrait_Expression_Enum_Empty_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL, substrait_Expression_Literal_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_VAR_CHAR, substrait_Expression_Literal_Var_Char_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_DECIMAL, substrait_Expression_Literal_Decimal_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_PRECISION_TIMESTAMP, substrait_Expression_Literal_Precision_Timestamp_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_MAP, substrait_Expression_Literal_Map_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_MAP_KEY_VALUE, substrait_Expression_Literal_Map_Key_Value_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_INTERVAL_YEAR_TO_MONTH, substrait_Expression_Literal_Interval_Year_To_Month_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_INTERVAL_DAY_TO_SECOND, substrait_Expression_Literal_Interval_Day_To_Second_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_INTERVAL_COMPOUND, substrait_Expression_Literal_Interval_Compound_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_STRUCT, substrait_Expression_Literal_Struct_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_LIST, substrait_Expression_Literal_List_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_LITERAL_USER_DEFINED, substrait_Expression_Literal_User_Defined_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_NESTED, substrait_Expression_Nested_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_NESTED_MAP, substrait_Expression_Nested_Map_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_NESTED_MAP_KEY_VALUE, substrait_Expression_Nested_Map_Key_Value_t, 2)


PB_BIND(SUBSTRAIT_EXPRESSION_NESTED_STRUCT, substrait_Expression_Nested_Struct_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_NESTED_LIST, substrait_Expression_Nested_List_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SCALAR_FUNCTION, substrait_Expression_Scalar_Function_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_WINDOW_FUNCTION, substrait_Expression_Window_Function_t, 2)


PB_BIND(SUBSTRAIT_EXPRESSION_WINDOW_FUNCTION_BOUND, substrait_Expression_Window_Function_Bound_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_WINDOW_FUNCTION_BOUND_PRECEDING, substrait_Expression_Window_Function_Bound_Preceding_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_WINDOW_FUNCTION_BOUND_FOLLOWING, substrait_Expression_Window_Function_Bound_Following_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_WINDOW_FUNCTION_BOUND_CURRENT_ROW, substrait_Expression_Window_Function_Bound_Current_Row_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_WINDOW_FUNCTION_BOUND_UNBOUNDED, substrait_Expression_Window_Function_Bound_Unbounded_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_IF_THEN, substrait_Expression_If_Then_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_IF_THEN_IF_CLAUSE, substrait_Expression_If_Then_If_Clause_t, 2)


PB_BIND(SUBSTRAIT_EXPRESSION_CAST, substrait_Expression_Cast_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SWITCH_EXPRESSION, substrait_Expression_Switch_Expression_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SWITCH_EXPRESSION_IF_VALUE, substrait_Expression_Switch_Expression_If_Value_t, 2)


PB_BIND(SUBSTRAIT_EXPRESSION_SINGULAR_OR_LIST, substrait_Expression_Singular_Or_List_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MULTI_OR_LIST, substrait_Expression_Multi_Or_List_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MULTI_OR_LIST_RECORD, substrait_Expression_Multi_Or_List_Record_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_EMBEDDED_FUNCTION, substrait_Expression_Embedded_Function_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_EMBEDDED_FUNCTION_PYTHON_PICKLE_FUNCTION, substrait_Expression_Embedded_Function_Python_Pickle_Function_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_EMBEDDED_FUNCTION_WEB_ASSEMBLY_FUNCTION, substrait_Expression_Embedded_Function_Web_Assembly_Function_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_REFERENCE_SEGMENT, substrait_Expression_Reference_Segment_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_REFERENCE_SEGMENT_MAP_KEY, substrait_Expression_Reference_Segment_Map_Key_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_REFERENCE_SEGMENT_STRUCT_FIELD, substrait_Expression_Reference_Segment_Struct_Field_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_REFERENCE_SEGMENT_LIST_ELEMENT, substrait_Expression_Reference_Segment_List_Element_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION, substrait_Expression_Mask_Expression_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_SELECT, substrait_Expression_Mask_Expression_Select_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_STRUCT_SELECT, substrait_Expression_Mask_Expression_Struct_Select_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_STRUCT_ITEM, substrait_Expression_Mask_Expression_Struct_Item_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_LIST_SELECT, substrait_Expression_Mask_Expression_List_Select_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_LIST_SELECT_LIST_SELECT_ITEM, substrait_Expression_Mask_Expression_List_Select_List_Select_Item_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_LIST_SELECT_LIST_SELECT_ITEM_LIST_ELEMENT, substrait_Expression_Mask_Expression_List_Select_List_Select_Item_List_Element_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_LIST_SELECT_LIST_SELECT_ITEM_LIST_SLICE, substrait_Expression_Mask_Expression_List_Select_List_Select_Item_List_Slice_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_MAP_SELECT, substrait_Expression_Mask_Expression_Map_Select_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_MAP_SELECT_MAP_KEY, substrait_Expression_Mask_Expression_Map_Select_Map_Key_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_MASK_EXPRESSION_MAP_SELECT_MAP_KEY_EXPRESSION, substrait_Expression_Mask_Expression_Map_Select_Map_Key_Expression_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_FIELD_REFERENCE, substrait_Expression_Field_Reference_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_FIELD_REFERENCE_ROOT_REFERENCE, substrait_Expression_Field_Reference_Root_Reference_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_FIELD_REFERENCE_OUTER_REFERENCE, substrait_Expression_Field_Reference_Outer_Reference_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SUBQUERY, substrait_Expression_Subquery_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SUBQUERY_SCALAR, substrait_Expression_Subquery_Scalar_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SUBQUERY_IN_PREDICATE, substrait_Expression_Subquery_In_Predicate_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SUBQUERY_SET_PREDICATE, substrait_Expression_Subquery_Set_Predicate_t, AUTO)


PB_BIND(SUBSTRAIT_EXPRESSION_SUBQUERY_SET_COMPARISON, substrait_Expression_Subquery_Set_Comparison_t, AUTO)


PB_BIND(SUBSTRAIT_DYNAMIC_PARAMETER, substrait_Dynamic_Parameter_t, AUTO)


PB_BIND(SUBSTRAIT_SORT_FIELD, substrait_Sort_Field_t, 2)


PB_BIND(SUBSTRAIT_AGGREGATE_FUNCTION, substrait_Aggregate_Function_t, AUTO)


PB_BIND(SUBSTRAIT_REFERENCE_REL, substrait_Reference_Rel_t, AUTO)











































#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

