/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_CAPABILITIES_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_CAPABILITIES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Defines a set of Capabilities that a system (producer or consumer) supports. */
typedef struct substrait_Capabilities {
    /* List of Substrait versions this system supports */
    pb_callback_t substrait_versions;
    /* list of com.google.Any message types this system supports for advanced
 extensions. */
    pb_callback_t advanced_extension_type_urls;
    /* list of simple extensions this system supports. */
    pb_callback_t simple_extensions;
} substrait_Capabilities_t;

typedef struct substrait_Capabilities_Simple_Extension {
    pb_callback_t uri;
    pb_callback_t function_keys;
    pb_callback_t type_keys;
    pb_callback_t type_variation_keys;
} substrait_Capabilities_Simple_Extension_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SUBSTRAIT_CAPABILITIES_INIT_DEFAULT      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_CAPABILITIES_INIT_ZERO         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_CAPABILITIES_SUBSTRAIT_VERSIONS_TAG 1
#define SUBSTRAIT_CAPABILITIES_ADVANCED_EXTENSION_TYPE_URLS_TAG 2
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSIONS_TAG 3
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_URI_TAG 1
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_FUNCTION_KEYS_TAG 2
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_TYPE_KEYS_TAG 3
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_TYPE_VARIATION_KEYS_TAG 4

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_CAPABILITIES_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   substrait_versions,   1) \
X(a, CALLBACK, REPEATED, STRING,   advanced_extension_type_urls,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  simple_extensions,   3)
#define SUBSTRAIT_CAPABILITIES_CALLBACK pb_default_field_callback
#define SUBSTRAIT_CAPABILITIES_DEFAULT NULL
#define substrait_Capabilities_t_simple_extensions_MSGTYPE substrait_Capabilities_Simple_Extension_t

#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   uri,               1) \
X(a, CALLBACK, REPEATED, STRING,   function_keys,     2) \
X(a, CALLBACK, REPEATED, STRING,   type_keys,         3) \
X(a, CALLBACK, REPEATED, STRING,   type_variation_keys,   4)
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_DEFAULT NULL

extern const pb_msgdesc_t substrait_Capabilities_t_msg;
extern const pb_msgdesc_t substrait_Capabilities_Simple_Extension_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_CAPABILITIES_FIELDS &substrait_Capabilities_t_msg
#define SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION_FIELDS &substrait_Capabilities_Simple_Extension_t_msg

/* Maximum encoded size of messages (where known) */
/* substrait_Capabilities_size depends on runtime parameters */
/* substrait_Capabilities_SimpleExtension_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
