/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "substrait/capabilities.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SUBSTRAIT_CAPABILITIES, substrait_Capabilities_t, AUTO)


PB_BIND(SUBSTRAIT_CAPABILITIES_SIMPLE_EXTENSION, substrait_Capabilities_Simple_Extension_t, AUTO)



