/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "substrait/extended_expression.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SUBSTRAIT_EXPRESSION_REFERENCE, substrait_Expression_Reference_t, 2)


PB_BIND(SUBSTRAIT_EXTENDED_EXPRESSION, substrait_Extended_Expression_t, 2)



