/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_EXTENDED_EXPRESSION_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_EXTENDED_EXPRESSION_PB_H_INCLUDED
#include <pb.h>
#include "substrait/algebra.pb.h"
#include "substrait/extensions/extensions.pb.h"
#include "substrait/plan.pb.h"
#include "substrait/type.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct substrait_Expression_Reference {
    pb_size_t which_expr_type;
    union substrait_Expression_Reference_expr_type {
        substrait_Expression_t expression;
        substrait_Aggregate_Function_t measure;
    } expr_type;
    /* Field names in depth-first order */
    pb_callback_t output_names;
} substrait_Expression_Reference_t;

/* Describe a set of operations to complete.
 For compactness sake, identifiers are normalized at the plan level. */
typedef struct substrait_Extended_Expression {
    /* a list of yaml specifications this expression may depend on */
    pb_callback_t extension_uris;
    /* a list of extensions this expression may depend on */
    pb_callback_t extensions;
    /* one or more expression trees with same order in plan rel */
    pb_callback_t referred_expr;
    bool has_base_schema;
    substrait_Named_Struct_t base_schema;
    /* additional extensions associated with this expression. */
    bool has_advanced_extensions;
    substrait_extensions_Advanced_Extension_t advanced_extensions;
    /* A list of com.google.Any entities that this plan may use. Can be used to
 warn if some embedded message types are unknown. Note that this list may
 include message types that are ignorable (optimizations) or that are
 unused. In many cases, a consumer may be able to work with a plan even if
 one or more message types defined here are unknown. */
    pb_callback_t expected_type_urls;
    /* Substrait version of the expression. Optional up to 0.17.0, required for later
 versions. */
    bool has_version;
    substrait_Version_t version;
} substrait_Extended_Expression_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SUBSTRAIT_EXPRESSION_REFERENCE_INIT_DEFAULT {0, {SUBSTRAIT_EXPRESSION_INIT_DEFAULT}, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENDED_EXPRESSION_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_NAMED_STRUCT_INIT_DEFAULT, false, SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_INIT_DEFAULT, {{NULL}, NULL}, false, SUBSTRAIT_VERSION_INIT_DEFAULT}
#define SUBSTRAIT_EXPRESSION_REFERENCE_INIT_ZERO {0, {SUBSTRAIT_EXPRESSION_INIT_ZERO}, {{NULL}, NULL}}
#define SUBSTRAIT_EXTENDED_EXPRESSION_INIT_ZERO  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_NAMED_STRUCT_INIT_ZERO, false, SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_INIT_ZERO, {{NULL}, NULL}, false, SUBSTRAIT_VERSION_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_EXPRESSION_REFERENCE_EXPRESSION_TAG 1
#define SUBSTRAIT_EXPRESSION_REFERENCE_MEASURE_TAG 2
#define SUBSTRAIT_EXPRESSION_REFERENCE_OUTPUT_NAMES_TAG 3
#define SUBSTRAIT_EXTENDED_EXPRESSION_EXTENSION_URIS_TAG 1
#define SUBSTRAIT_EXTENDED_EXPRESSION_EXTENSIONS_TAG 2
#define SUBSTRAIT_EXTENDED_EXPRESSION_REFERRED_EXPR_TAG 3
#define SUBSTRAIT_EXTENDED_EXPRESSION_BASE_SCHEMA_TAG 4
#define SUBSTRAIT_EXTENDED_EXPRESSION_ADVANCED_EXTENSIONS_TAG 5
#define SUBSTRAIT_EXTENDED_EXPRESSION_EXPECTED_TYPE_URLS_TAG 6
#define SUBSTRAIT_EXTENDED_EXPRESSION_VERSION_TAG 7

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_EXPRESSION_REFERENCE_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (expr_type,expression,expr_type.expression),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (expr_type,measure,expr_type.measure),   2) \
X(a, CALLBACK, REPEATED, STRING,   output_names,      3)
#define SUBSTRAIT_EXPRESSION_REFERENCE_CALLBACK pb_default_field_callback
#define SUBSTRAIT_EXPRESSION_REFERENCE_DEFAULT NULL
#define substrait_Expression_Reference_t_expr_type_expression_MSGTYPE substrait_Expression_t
#define substrait_Expression_Reference_t_expr_type_measure_MSGTYPE substrait_Aggregate_Function_t

#define SUBSTRAIT_EXTENDED_EXPRESSION_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  extension_uris,    1) \
X(a, CALLBACK, REPEATED, MESSAGE,  extensions,        2) \
X(a, CALLBACK, REPEATED, MESSAGE,  referred_expr,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  base_schema,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  advanced_extensions,   5) \
X(a, CALLBACK, REPEATED, STRING,   expected_type_urls,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           7)
#define SUBSTRAIT_EXTENDED_EXPRESSION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_EXTENDED_EXPRESSION_DEFAULT NULL
#define substrait_Extended_Expression_t_extension_uris_MSGTYPE substrait_extensions_Simple_Extension_URI_t
#define substrait_Extended_Expression_t_extensions_MSGTYPE substrait_extensions_Simple_Extension_Declaration_t
#define substrait_Extended_Expression_t_referred_expr_MSGTYPE substrait_Expression_Reference_t
#define substrait_Extended_Expression_t_base_schema_MSGTYPE substrait_Named_Struct_t
#define substrait_Extended_Expression_t_advanced_extensions_MSGTYPE substrait_extensions_Advanced_Extension_t
#define substrait_Extended_Expression_t_version_MSGTYPE substrait_Version_t

extern const pb_msgdesc_t substrait_Expression_Reference_t_msg;
extern const pb_msgdesc_t substrait_Extended_Expression_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_EXPRESSION_REFERENCE_FIELDS &substrait_Expression_Reference_t_msg
#define SUBSTRAIT_EXTENDED_EXPRESSION_FIELDS &substrait_Extended_Expression_t_msg

/* Maximum encoded size of messages (where known) */
#if defined(substrait_Expression_size) && defined(substrait_AggregateFunction_size)
union substrait_ExpressionReference_expr_type_size_union {char f1[(6 + substrait_Expression_size)]; char f2[(6 + substrait_AggregateFunction_size)];};
#endif
/* substrait_ExpressionReference_size depends on runtime parameters */
/* substrait_ExtendedExpression_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
