/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_FUNCTION_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_FUNCTION_PB_H_INCLUDED
#include <pb.h>
#include "substrait/parameterized_types.pb.h"
#include "substrait/type.pb.h"
#include "substrait/type_expressions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum substrait_Function_Signature_Final_Arg_Variadic_Parameter_Consistency {
    SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_PARAMETER_CONSISTENCY_UNSPECIFIED = 0,
    /* All argument must be the same concrete type. */
    SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_PARAMETER_CONSISTENCY_CONSISTENT = 1,
    /* Each argument can be any possible concrete type afforded by the bounds
 of any parameter defined in the arguments specification. */
    SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_PARAMETER_CONSISTENCY_INCONSISTENT = 2
} substrait_Function_Signature_Final_Arg_Variadic_Parameter_Consistency_t;

typedef enum substrait_Function_Signature_Window_Window_Type {
    SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_WINDOW_TYPE_UNSPECIFIED = 0,
    SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_WINDOW_TYPE_STREAMING = 1,
    SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_WINDOW_TYPE_PARTITION = 2
} substrait_Function_Signature_Window_Window_Type_t;

typedef enum substrait_Function_Signature_Implementation_Type {
    SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_TYPE_UNSPECIFIED = 0,
    SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_TYPE_WEB_ASSEMBLY = 1,
    SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_TYPE_TRINO_JAR = 2
} substrait_Function_Signature_Implementation_Type_t;

/* Struct definitions */
/* List of function signatures available. */
typedef struct substrait_Function_Signature {
    char dummy_field;
} substrait_Function_Signature_t;

typedef struct substrait_Function_Signature_Final_Arg_Variadic {
    /* the minimum number of arguments allowed for the list of final arguments
 (inclusive). */
    int64_t min_args;
    /* the maximum number of arguments allowed for the list of final arguments
 (exclusive) */
    int64_t max_args;
    /* the type of parameterized type consistency */
    substrait_Function_Signature_Final_Arg_Variadic_Parameter_Consistency_t consistency;
} substrait_Function_Signature_Final_Arg_Variadic_t;

typedef struct substrait_Function_Signature_Final_Arg_Normal {
    char dummy_field;
} substrait_Function_Signature_Final_Arg_Normal_t;

typedef struct substrait_Function_Signature_Description {
    pb_callback_t language;
    pb_callback_t body;
} substrait_Function_Signature_Description_t;

typedef struct substrait_Function_Signature_Scalar {
    pb_callback_t arguments;
    pb_callback_t name;
    bool has_description;
    substrait_Function_Signature_Description_t description;
    bool deterministic;
    bool session_dependent;
    bool has_output_type;
    substrait_Derivation_Expression_t output_type;
    pb_size_t which_final_variable_behavior;
    union substrait_Function_Signature_Scalar_final_variable_behavior {
        substrait_Function_Signature_Final_Arg_Variadic_t variadic;
        substrait_Function_Signature_Final_Arg_Normal_t normal;
    } final_variable_behavior;
    pb_callback_t implementations;
} substrait_Function_Signature_Scalar_t;

typedef struct substrait_Function_Signature_Aggregate {
    pb_callback_t arguments;
    pb_callback_t name;
    bool has_description;
    substrait_Function_Signature_Description_t description;
    bool deterministic;
    bool session_dependent;
    bool has_output_type;
    substrait_Derivation_Expression_t output_type;
    pb_size_t which_final_variable_behavior;
    union substrait_Function_Signature_Aggregate_final_variable_behavior {
        substrait_Function_Signature_Final_Arg_Variadic_t variadic;
        substrait_Function_Signature_Final_Arg_Normal_t normal;
    } final_variable_behavior;
    uint64_t max_set;
    bool has_intermediate_type;
    substrait_Type_t intermediate_type;
    bool ordered;
    pb_callback_t implementations;
} substrait_Function_Signature_Aggregate_t;

typedef struct substrait_Function_Signature_Window {
    pb_callback_t arguments;
    pb_callback_t name;
    bool has_description;
    substrait_Function_Signature_Description_t description;
    bool deterministic;
    bool session_dependent;
    bool has_intermediate_type;
    substrait_Derivation_Expression_t intermediate_type;
    bool has_output_type;
    substrait_Derivation_Expression_t output_type;
    bool ordered;
    uint64_t max_set;
    substrait_Function_Signature_Window_Window_Type_t window_type;
    pb_callback_t implementations;
    pb_size_t which_final_variable_behavior;
    union substrait_Function_Signature_Window_final_variable_behavior {
        substrait_Function_Signature_Final_Arg_Variadic_t variadic;
        substrait_Function_Signature_Final_Arg_Normal_t normal;
    } final_variable_behavior;
} substrait_Function_Signature_Window_t;

typedef struct substrait_Function_Signature_Implementation {
    substrait_Function_Signature_Implementation_Type_t type;
    pb_callback_t uri;
} substrait_Function_Signature_Implementation_t;

typedef struct substrait_Function_Signature_Argument_Value_Argument {
    bool has_type;
    substrait_Parameterized_Type_t type;
    bool constant;
} substrait_Function_Signature_Argument_Value_Argument_t;

typedef struct substrait_Function_Signature_Argument_Type_Argument {
    bool has_type;
    substrait_Parameterized_Type_t type;
} substrait_Function_Signature_Argument_Type_Argument_t;

typedef struct substrait_Function_Signature_Argument_Enum_Argument {
    pb_callback_t options;
    bool optional;
} substrait_Function_Signature_Argument_Enum_Argument_t;

typedef struct substrait_Function_Signature_Argument {
    pb_callback_t name;
    pb_size_t which_argument_kind;
    union substrait_Function_Signature_Argument_argument_kind {
        substrait_Function_Signature_Argument_Value_Argument_t value;
        substrait_Function_Signature_Argument_Type_Argument_t type;
        substrait_Function_Signature_Argument_Enum_Argument_t enum_;
    } argument_kind;
} substrait_Function_Signature_Argument_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_MIN SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_PARAMETER_CONSISTENCY_UNSPECIFIED
#define _SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_MAX SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_PARAMETER_CONSISTENCY_INCONSISTENT
#define _SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_ARRAYSIZE ((substrait_Function_Signature_Final_Arg_Variadic_Parameter_Consistency_t)(SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_PARAMETER_CONSISTENCY_INCONSISTENT+1))

#define _SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_MIN SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_WINDOW_TYPE_UNSPECIFIED
#define _SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_MAX SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_WINDOW_TYPE_PARTITION
#define _SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_ARRAYSIZE ((substrait_Function_Signature_Window_Window_Type_t)(SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_WINDOW_TYPE_PARTITION+1))

#define _SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_MIN SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_TYPE_UNSPECIFIED
#define _SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_MAX SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_TYPE_TRINO_JAR
#define _SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_ARRAYSIZE ((substrait_Function_Signature_Implementation_Type_t)(SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_TYPE_TRINO_JAR+1))


#define substrait_Function_Signature_Final_Arg_Variadic_t_consistency_ENUMTYPE substrait_Function_Signature_Final_Arg_Variadic_Parameter_Consistency_t




#define substrait_Function_Signature_Window_t_window_type_ENUMTYPE substrait_Function_Signature_Window_Window_Type_t


#define substrait_Function_Signature_Implementation_t_type_ENUMTYPE substrait_Function_Signature_Implementation_Type_t






/* Initializer values for message structs */
#define SUBSTRAIT_FUNCTION_SIGNATURE_INIT_DEFAULT {0}
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_DEFAULT {0, 0, _SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_MIN}
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL_INIT_DEFAULT {0}
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_DEFAULT, 0, 0, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_DEFAULT, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_DEFAULT}, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_DEFAULT, 0, 0, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_DEFAULT, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_DEFAULT}, 0, false, SUBSTRAIT_TYPE_INIT_DEFAULT, 0, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_DEFAULT, 0, 0, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_DEFAULT, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_DEFAULT, 0, 0, _SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_MIN, {{NULL}, NULL}, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_DEFAULT}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_INIT_DEFAULT {_SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_MIN, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_INIT_DEFAULT {{{NULL}, NULL}, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_INIT_DEFAULT}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INIT_DEFAULT, 0}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INIT_DEFAULT}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_INIT_DEFAULT {{{NULL}, NULL}, 0}
#define SUBSTRAIT_FUNCTION_SIGNATURE_INIT_ZERO   {0}
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_ZERO {0, 0, _SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_PARAMETER_CONSISTENCY_MIN}
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL_INIT_ZERO {0}
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_ZERO, 0, 0, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_ZERO, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_ZERO}, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_ZERO, 0, 0, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_ZERO, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_ZERO}, 0, false, SUBSTRAIT_TYPE_INIT_ZERO, 0, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_ZERO, 0, 0, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_ZERO, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_ZERO, 0, 0, _SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_MIN, {{NULL}, NULL}, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_INIT_ZERO}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_INIT_ZERO {_SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_MIN, {{NULL}, NULL}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_INIT_ZERO {{{NULL}, NULL}, 0, {SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_INIT_ZERO}}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INIT_ZERO, 0}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INIT_ZERO}
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_INIT_ZERO {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_MIN_ARGS_TAG 1
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_MAX_ARGS_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_CONSISTENCY_TAG 3
#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_LANGUAGE_TAG 1
#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_BODY_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_ARGUMENTS_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_NAME_TAG 3
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_DESCRIPTION_TAG 4
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_DETERMINISTIC_TAG 7
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_SESSION_DEPENDENT_TAG 8
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_OUTPUT_TYPE_TAG 9
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_VARIADIC_TAG 10
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_NORMAL_TAG 11
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_IMPLEMENTATIONS_TAG 12
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_ARGUMENTS_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_NAME_TAG 3
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_DESCRIPTION_TAG 4
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_DETERMINISTIC_TAG 7
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_SESSION_DEPENDENT_TAG 8
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_OUTPUT_TYPE_TAG 9
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_VARIADIC_TAG 10
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_NORMAL_TAG 11
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_MAX_SET_TAG 12
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_INTERMEDIATE_TYPE_TAG 13
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_ORDERED_TAG 14
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_IMPLEMENTATIONS_TAG 15
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_ARGUMENTS_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_NAME_TAG 3
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_DESCRIPTION_TAG 4
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_DETERMINISTIC_TAG 7
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_SESSION_DEPENDENT_TAG 8
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_INTERMEDIATE_TYPE_TAG 9
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_OUTPUT_TYPE_TAG 10
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_ORDERED_TAG 11
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_MAX_SET_TAG 12
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_WINDOW_TYPE_TAG 14
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_IMPLEMENTATIONS_TAG 15
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_VARIADIC_TAG 16
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_NORMAL_TAG 17
#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_TYPE_TAG 1
#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_URI_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_TYPE_TAG 1
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_CONSTANT_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_TYPE_TAG 1
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_OPTIONS_TAG 1
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_OPTIONAL_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_NAME_TAG 1
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_TAG 2
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_TAG 3
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_TAG 4

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_FUNCTION_SIGNATURE_FIELDLIST(X, a) \

#define SUBSTRAIT_FUNCTION_SIGNATURE_CALLBACK NULL
#define SUBSTRAIT_FUNCTION_SIGNATURE_DEFAULT NULL

#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    min_args,          1) \
X(a, STATIC,   SINGULAR, INT64,    max_args,          2) \
X(a, STATIC,   SINGULAR, UENUM,    consistency,       3)
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_CALLBACK NULL
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_DEFAULT NULL

#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL_FIELDLIST(X, a) \

#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL_CALLBACK NULL
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL_DEFAULT NULL

#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2) \
X(a, CALLBACK, REPEATED, STRING,   name,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  description,       4) \
X(a, STATIC,   SINGULAR, BOOL,     deterministic,     7) \
X(a, STATIC,   SINGULAR, BOOL,     session_dependent,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  output_type,       9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (final_variable_behavior,variadic,final_variable_behavior.variadic),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (final_variable_behavior,normal,final_variable_behavior.normal),  11) \
X(a, CALLBACK, REPEATED, MESSAGE,  implementations,  12)
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_CALLBACK pb_default_field_callback
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_DEFAULT NULL
#define substrait_Function_Signature_Scalar_t_arguments_MSGTYPE substrait_Function_Signature_Argument_t
#define substrait_Function_Signature_Scalar_t_description_MSGTYPE substrait_Function_Signature_Description_t
#define substrait_Function_Signature_Scalar_t_output_type_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Function_Signature_Scalar_t_final_variable_behavior_variadic_MSGTYPE substrait_Function_Signature_Final_Arg_Variadic_t
#define substrait_Function_Signature_Scalar_t_final_variable_behavior_normal_MSGTYPE substrait_Function_Signature_Final_Arg_Normal_t
#define substrait_Function_Signature_Scalar_t_implementations_MSGTYPE substrait_Function_Signature_Implementation_t

#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  description,       4) \
X(a, STATIC,   SINGULAR, BOOL,     deterministic,     7) \
X(a, STATIC,   SINGULAR, BOOL,     session_dependent,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  output_type,       9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (final_variable_behavior,variadic,final_variable_behavior.variadic),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (final_variable_behavior,normal,final_variable_behavior.normal),  11) \
X(a, STATIC,   SINGULAR, UINT64,   max_set,          12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  intermediate_type,  13) \
X(a, STATIC,   SINGULAR, BOOL,     ordered,          14) \
X(a, CALLBACK, REPEATED, MESSAGE,  implementations,  15)
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_CALLBACK pb_default_field_callback
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_DEFAULT NULL
#define substrait_Function_Signature_Aggregate_t_arguments_MSGTYPE substrait_Function_Signature_Argument_t
#define substrait_Function_Signature_Aggregate_t_description_MSGTYPE substrait_Function_Signature_Description_t
#define substrait_Function_Signature_Aggregate_t_output_type_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Function_Signature_Aggregate_t_final_variable_behavior_variadic_MSGTYPE substrait_Function_Signature_Final_Arg_Variadic_t
#define substrait_Function_Signature_Aggregate_t_final_variable_behavior_normal_MSGTYPE substrait_Function_Signature_Final_Arg_Normal_t
#define substrait_Function_Signature_Aggregate_t_intermediate_type_MSGTYPE substrait_Type_t
#define substrait_Function_Signature_Aggregate_t_implementations_MSGTYPE substrait_Function_Signature_Implementation_t

#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2) \
X(a, CALLBACK, REPEATED, STRING,   name,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  description,       4) \
X(a, STATIC,   SINGULAR, BOOL,     deterministic,     7) \
X(a, STATIC,   SINGULAR, BOOL,     session_dependent,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  intermediate_type,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  output_type,      10) \
X(a, STATIC,   SINGULAR, BOOL,     ordered,          11) \
X(a, STATIC,   SINGULAR, UINT64,   max_set,          12) \
X(a, STATIC,   SINGULAR, UENUM,    window_type,      14) \
X(a, CALLBACK, REPEATED, MESSAGE,  implementations,  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (final_variable_behavior,variadic,final_variable_behavior.variadic),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (final_variable_behavior,normal,final_variable_behavior.normal),  17)
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_CALLBACK pb_default_field_callback
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_DEFAULT NULL
#define substrait_Function_Signature_Window_t_arguments_MSGTYPE substrait_Function_Signature_Argument_t
#define substrait_Function_Signature_Window_t_description_MSGTYPE substrait_Function_Signature_Description_t
#define substrait_Function_Signature_Window_t_intermediate_type_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Function_Signature_Window_t_output_type_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Function_Signature_Window_t_implementations_MSGTYPE substrait_Function_Signature_Implementation_t
#define substrait_Function_Signature_Window_t_final_variable_behavior_variadic_MSGTYPE substrait_Function_Signature_Final_Arg_Variadic_t
#define substrait_Function_Signature_Window_t_final_variable_behavior_normal_MSGTYPE substrait_Function_Signature_Final_Arg_Normal_t

#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   language,          1) \
X(a, CALLBACK, SINGULAR, STRING,   body,              2)
#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_DEFAULT NULL

#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   uri,               2)
#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_DEFAULT NULL

#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (argument_kind,value,argument_kind.value),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (argument_kind,type,argument_kind.type),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (argument_kind,enum_,argument_kind.enum_),   4)
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_DEFAULT NULL
#define substrait_Function_Signature_Argument_t_argument_kind_value_MSGTYPE substrait_Function_Signature_Argument_Value_Argument_t
#define substrait_Function_Signature_Argument_t_argument_kind_type_MSGTYPE substrait_Function_Signature_Argument_Type_Argument_t
#define substrait_Function_Signature_Argument_t_argument_kind_enum__MSGTYPE substrait_Function_Signature_Argument_Enum_Argument_t

#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  type,              1) \
X(a, STATIC,   SINGULAR, BOOL,     constant,          2)
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_CALLBACK NULL
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_DEFAULT NULL
#define substrait_Function_Signature_Argument_Value_Argument_t_type_MSGTYPE substrait_Parameterized_Type_t

#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  type,              1)
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_CALLBACK NULL
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_DEFAULT NULL
#define substrait_Function_Signature_Argument_Type_Argument_t_type_MSGTYPE substrait_Parameterized_Type_t

#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   options,           1) \
X(a, STATIC,   SINGULAR, BOOL,     optional,          2)
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_DEFAULT NULL

extern const pb_msgdesc_t substrait_Function_Signature_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Final_Arg_Variadic_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Final_Arg_Normal_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Scalar_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Aggregate_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Window_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Description_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Implementation_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Argument_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Argument_Value_Argument_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Argument_Type_Argument_t_msg;
extern const pb_msgdesc_t substrait_Function_Signature_Argument_Enum_Argument_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_FUNCTION_SIGNATURE_FIELDS &substrait_Function_Signature_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_FIELDS &substrait_Function_Signature_Final_Arg_Variadic_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL_FIELDS &substrait_Function_Signature_Final_Arg_Normal_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR_FIELDS &substrait_Function_Signature_Scalar_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE_FIELDS &substrait_Function_Signature_Aggregate_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW_FIELDS &substrait_Function_Signature_Window_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION_FIELDS &substrait_Function_Signature_Description_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION_FIELDS &substrait_Function_Signature_Implementation_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_FIELDS &substrait_Function_Signature_Argument_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_FIELDS &substrait_Function_Signature_Argument_Value_Argument_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_FIELDS &substrait_Function_Signature_Argument_Type_Argument_t_msg
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT_FIELDS &substrait_Function_Signature_Argument_Enum_Argument_t_msg

/* Maximum encoded size of messages (where known) */
/* substrait_FunctionSignature_Scalar_size depends on runtime parameters */
/* substrait_FunctionSignature_Aggregate_size depends on runtime parameters */
/* substrait_FunctionSignature_Window_size depends on runtime parameters */
/* substrait_FunctionSignature_Description_size depends on runtime parameters */
/* substrait_FunctionSignature_Implementation_size depends on runtime parameters */
/* substrait_FunctionSignature_Argument_size depends on runtime parameters */
/* substrait_FunctionSignature_Argument_EnumArgument_size depends on runtime parameters */
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL_SIZE 0
#define SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_SIZE 24
#define SUBSTRAIT_FUNCTION_SIGNATURE_SIZE        0
#define SUBSTRAIT_SUBSTRAIT_FUNCTION_PB_H_MAX_SIZE SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC_SIZE
#if defined(substrait_ParameterizedType_size)
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT_SIZE (6 + substrait_ParameterizedType_size)
#define SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT_SIZE (8 + substrait_ParameterizedType_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
