/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "substrait/function.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE, substrait_Function_Signature_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_VARIADIC, substrait_Function_Signature_Final_Arg_Variadic_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_FINAL_ARG_NORMAL, substrait_Function_Signature_Final_Arg_Normal_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_SCALAR, substrait_Function_Signature_Scalar_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_AGGREGATE, substrait_Function_Signature_Aggregate_t, 2)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_WINDOW, substrait_Function_Signature_Window_t, 2)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_DESCRIPTION, substrait_Function_Signature_Description_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_IMPLEMENTATION, substrait_Function_Signature_Implementation_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT, substrait_Function_Signature_Argument_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_VALUE_ARGUMENT, substrait_Function_Signature_Argument_Value_Argument_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_TYPE_ARGUMENT, substrait_Function_Signature_Argument_Type_Argument_t, AUTO)


PB_BIND(SUBSTRAIT_FUNCTION_SIGNATURE_ARGUMENT_ENUM_ARGUMENT, substrait_Function_Signature_Argument_Enum_Argument_t, AUTO)









