/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_PARAMETERIZED_TYPES_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_PARAMETERIZED_TYPES_PB_H_INCLUDED
#include <pb.h>
#include "substrait/type.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct substrait_Parameterized_Type_Type_Parameter {
    pb_callback_t name;
    pb_callback_t bounds;
} substrait_Parameterized_Type_Type_Parameter_t;

typedef struct substrait_Parameterized_Type_Nullable_Integer {
    int64_t value;
} substrait_Parameterized_Type_Nullable_Integer_t;

typedef struct substrait_Parameterized_Type_Integer_Parameter {
    pb_callback_t name;
    bool has_range_start_inclusive;
    substrait_Parameterized_Type_Nullable_Integer_t range_start_inclusive;
    bool has_range_end_exclusive;
    substrait_Parameterized_Type_Nullable_Integer_t range_end_exclusive;
} substrait_Parameterized_Type_Integer_Parameter_t;

typedef struct substrait_Parameterized_Type_Parameterized_Struct {
    pb_callback_t types;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Struct_t;

typedef struct substrait_Parameterized_Type_Parameterized_Named_Struct {
    /* list of names in dfs order */
    pb_callback_t names;
    bool has_struct_;
    substrait_Parameterized_Type_Parameterized_Struct_t struct_;
} substrait_Parameterized_Type_Parameterized_Named_Struct_t;

typedef struct substrait_Parameterized_Type_Parameterized_List {
    pb_callback_t type;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Parameterized_Type_Parameterized_List_t;

typedef struct substrait_Parameterized_Type_Parameterized_Map {
    pb_callback_t key;
    pb_callback_t value;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Parameterized_Type_Parameterized_Map_t;

typedef struct substrait_Parameterized_Type_Parameterized_User_Defined {
    uint32_t type_pointer;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_User_Defined_t;

typedef struct substrait_Parameterized_Type_Integer_Option {
    pb_size_t which_integer_type;
    union substrait_Parameterized_Type_Integer_Option_integer_type {
        int32_t literal;
        substrait_Parameterized_Type_Integer_Parameter_t parameter;
    } integer_type;
} substrait_Parameterized_Type_Integer_Option_t;

typedef struct substrait_Parameterized_Type_Parameterized_Fixed_Char {
    bool has_length;
    substrait_Parameterized_Type_Integer_Option_t length;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Fixed_Char_t;

typedef struct substrait_Parameterized_Type_Parameterized_Var_Char {
    bool has_length;
    substrait_Parameterized_Type_Integer_Option_t length;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Var_Char_t;

typedef struct substrait_Parameterized_Type_Parameterized_Fixed_Binary {
    bool has_length;
    substrait_Parameterized_Type_Integer_Option_t length;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Fixed_Binary_t;

typedef struct substrait_Parameterized_Type_Parameterized_Decimal {
    bool has_scale;
    substrait_Parameterized_Type_Integer_Option_t scale;
    bool has_precision;
    substrait_Parameterized_Type_Integer_Option_t precision;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Decimal_t;

typedef struct substrait_Parameterized_Type_Parameterized_Interval_Day {
    bool has_precision;
    substrait_Parameterized_Type_Integer_Option_t precision;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Interval_Day_t;

typedef struct substrait_Parameterized_Type_Parameterized_Interval_Compound {
    bool has_precision;
    substrait_Parameterized_Type_Integer_Option_t precision;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Interval_Compound_t;

typedef struct substrait_Parameterized_Type_Parameterized_Precision_Timestamp {
    bool has_precision;
    substrait_Parameterized_Type_Integer_Option_t precision;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Precision_Timestamp_t;

typedef struct substrait_Parameterized_Type_Parameterized_Precision_Timestamp_TZ {
    bool has_precision;
    substrait_Parameterized_Type_Integer_Option_t precision;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Parameterized_Type_Parameterized_Precision_Timestamp_TZ_t;

typedef struct substrait_Parameterized_Type {
    pb_size_t which_kind;
    union substrait_Parameterized_Type_kind {
        substrait_Type_Boolean_t bool_;
        substrait_Type_I8_t i8;
        substrait_Type_I16_t i16;
        substrait_Type_I32_t i32;
        substrait_Type_I64_t i64;
        substrait_Type_FP32_t fp32;
        substrait_Type_FP64_t fp64;
        substrait_Type_String_t string;
        substrait_Type_Binary_t binary;
        /* Deprecated in favor of `ParameterizedPrecisionTimestamp precision_timestamp` */
        substrait_Type_Timestamp_t timestamp;
        substrait_Type_Date_t date;
        substrait_Type_Time_t time;
        substrait_Type_Interval_Year_t interval_year;
        substrait_Parameterized_Type_Parameterized_Interval_Day_t interval_day;
        substrait_Parameterized_Type_Parameterized_Fixed_Char_t fixed_char;
        substrait_Parameterized_Type_Parameterized_Var_Char_t varchar;
        substrait_Parameterized_Type_Parameterized_Fixed_Binary_t fixed_binary;
        substrait_Parameterized_Type_Parameterized_Decimal_t decimal;
        substrait_Parameterized_Type_Parameterized_Struct_t struct_;
        substrait_Parameterized_Type_Parameterized_List_t list;
        substrait_Parameterized_Type_Parameterized_Map_t map;
        /* Deprecated in favor of `ParameterizedPrecisionTimestampTZ precision_timestamp_tz` */
        substrait_Type_Timestamp_TZ_t timestamp_tz;
        substrait_Parameterized_Type_Parameterized_User_Defined_t user_defined;
        /* Deprecated in favor of user_defined, which allows nullability and
     variations to be specified. If user_defined_pointer is encountered,
     treat it as being non-nullable and having the default variation. */
        uint32_t user_defined_pointer;
        substrait_Type_UUID_t uuid;
        substrait_Parameterized_Type_Type_Parameter_t type_parameter;
        substrait_Parameterized_Type_Parameterized_Precision_Timestamp_t precision_timestamp;
        substrait_Parameterized_Type_Parameterized_Precision_Timestamp_TZ_t precision_timestamp_tz;
        substrait_Parameterized_Type_Parameterized_Interval_Compound_t interval_compound;
    } kind;
} substrait_Parameterized_Type_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SUBSTRAIT_PARAMETERIZED_TYPE_INIT_DEFAULT {0, {SUBSTRAIT_TYPE_BOOLEAN_INIT_DEFAULT}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_INIT_DEFAULT {{{NULL}, NULL}, false, SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_INIT_DEFAULT, false, SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_INIT_DEFAULT}
#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_INIT_DEFAULT {0}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_INIT_DEFAULT {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_INIT_DEFAULT {{{NULL}, NULL}, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_INIT_DEFAULT {{{NULL}, NULL}, false, SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_INIT_DEFAULT}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_INIT_DEFAULT {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_DEFAULT {0, {0}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_INIT_ZERO   {0, {SUBSTRAIT_TYPE_BOOLEAN_INIT_ZERO}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_INIT_ZERO {{{NULL}, NULL}, false, SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_INIT_ZERO, false, SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_INIT_ZERO}
#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_INIT_ZERO {0}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_INIT_ZERO {false, SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_INIT_ZERO {{{NULL}, NULL}, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_INIT_ZERO {{{NULL}, NULL}, false, SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_INIT_ZERO}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_INIT_ZERO {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_INIT_ZERO {0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_NAME_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_BOUNDS_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_VALUE_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_NAME_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_RANGE_START_INCLUSIVE_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_RANGE_END_EXCLUSIVE_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_TYPES_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_NAMES_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_STRUCT_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_TYPE_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_KEY_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_VALUE_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_VARIATION_POINTER_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_NULLABILITY_TAG 4
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_TYPE_POINTER_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_LITERAL_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_PARAMETER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_LENGTH_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_LENGTH_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_LENGTH_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_SCALE_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_PRECISION_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_VARIATION_POINTER_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_NULLABILITY_TAG 4
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_PRECISION_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_PRECISION_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_PRECISION_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_PRECISION_TAG 1
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_NULLABILITY_TAG 3
#define SUBSTRAIT_PARAMETERIZED_TYPE_BOOL_TAG    1
#define SUBSTRAIT_PARAMETERIZED_TYPE_I8_TAG      2
#define SUBSTRAIT_PARAMETERIZED_TYPE_I16_TAG     3
#define SUBSTRAIT_PARAMETERIZED_TYPE_I32_TAG     5
#define SUBSTRAIT_PARAMETERIZED_TYPE_I64_TAG     7
#define SUBSTRAIT_PARAMETERIZED_TYPE_FP32_TAG    10
#define SUBSTRAIT_PARAMETERIZED_TYPE_FP64_TAG    11
#define SUBSTRAIT_PARAMETERIZED_TYPE_STRING_TAG  12
#define SUBSTRAIT_PARAMETERIZED_TYPE_BINARY_TAG  13
#define SUBSTRAIT_PARAMETERIZED_TYPE_TIMESTAMP_TAG 14
#define SUBSTRAIT_PARAMETERIZED_TYPE_DATE_TAG    16
#define SUBSTRAIT_PARAMETERIZED_TYPE_TIME_TAG    17
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTERVAL_YEAR_TAG 19
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTERVAL_DAY_TAG 20
#define SUBSTRAIT_PARAMETERIZED_TYPE_FIXED_CHAR_TAG 21
#define SUBSTRAIT_PARAMETERIZED_TYPE_VARCHAR_TAG 22
#define SUBSTRAIT_PARAMETERIZED_TYPE_FIXED_BINARY_TAG 23
#define SUBSTRAIT_PARAMETERIZED_TYPE_DECIMAL_TAG 24
#define SUBSTRAIT_PARAMETERIZED_TYPE_STRUCT_TAG  25
#define SUBSTRAIT_PARAMETERIZED_TYPE_LIST_TAG    27
#define SUBSTRAIT_PARAMETERIZED_TYPE_MAP_TAG     28
#define SUBSTRAIT_PARAMETERIZED_TYPE_TIMESTAMP_TZ_TAG 29
#define SUBSTRAIT_PARAMETERIZED_TYPE_USER_DEFINED_TAG 30
#define SUBSTRAIT_PARAMETERIZED_TYPE_USER_DEFINED_POINTER_TAG 31
#define SUBSTRAIT_PARAMETERIZED_TYPE_UUID_TAG    32
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_TAG 33
#define SUBSTRAIT_PARAMETERIZED_TYPE_PRECISION_TIMESTAMP_TAG 34
#define SUBSTRAIT_PARAMETERIZED_TYPE_PRECISION_TIMESTAMP_TZ_TAG 35
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTERVAL_COMPOUND_TAG 36

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_PARAMETERIZED_TYPE_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,bool_,kind.bool_),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i8,kind.i8),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i16,kind.i16),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i32,kind.i32),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i64,kind.i64),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fp32,kind.fp32),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fp64,kind.fp64),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,string,kind.string),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,binary,kind.binary),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,timestamp,kind.timestamp),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,date,kind.date),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,time,kind.time),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_year,kind.interval_year),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_day,kind.interval_day),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fixed_char,kind.fixed_char),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,varchar,kind.varchar),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fixed_binary,kind.fixed_binary),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,decimal,kind.decimal),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,struct_,kind.struct_),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,list,kind.list),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,map,kind.map),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,timestamp_tz,kind.timestamp_tz),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,user_defined,kind.user_defined),  30) \
X(a, STATIC,   ONEOF,    UINT32,   (kind,user_defined_pointer,kind.user_defined_pointer),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,uuid,kind.uuid),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,type_parameter,kind.type_parameter),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,precision_timestamp,kind.precision_timestamp),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,precision_timestamp_tz,kind.precision_timestamp_tz),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_compound,kind.interval_compound),  36)
#define SUBSTRAIT_PARAMETERIZED_TYPE_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_DEFAULT NULL
#define substrait_Parameterized_Type_t_kind_bool__MSGTYPE substrait_Type_Boolean_t
#define substrait_Parameterized_Type_t_kind_i8_MSGTYPE substrait_Type_I8_t
#define substrait_Parameterized_Type_t_kind_i16_MSGTYPE substrait_Type_I16_t
#define substrait_Parameterized_Type_t_kind_i32_MSGTYPE substrait_Type_I32_t
#define substrait_Parameterized_Type_t_kind_i64_MSGTYPE substrait_Type_I64_t
#define substrait_Parameterized_Type_t_kind_fp32_MSGTYPE substrait_Type_FP32_t
#define substrait_Parameterized_Type_t_kind_fp64_MSGTYPE substrait_Type_FP64_t
#define substrait_Parameterized_Type_t_kind_string_MSGTYPE substrait_Type_String_t
#define substrait_Parameterized_Type_t_kind_binary_MSGTYPE substrait_Type_Binary_t
#define substrait_Parameterized_Type_t_kind_timestamp_MSGTYPE substrait_Type_Timestamp_t
#define substrait_Parameterized_Type_t_kind_date_MSGTYPE substrait_Type_Date_t
#define substrait_Parameterized_Type_t_kind_time_MSGTYPE substrait_Type_Time_t
#define substrait_Parameterized_Type_t_kind_interval_year_MSGTYPE substrait_Type_Interval_Year_t
#define substrait_Parameterized_Type_t_kind_interval_day_MSGTYPE substrait_Parameterized_Type_Parameterized_Interval_Day_t
#define substrait_Parameterized_Type_t_kind_fixed_char_MSGTYPE substrait_Parameterized_Type_Parameterized_Fixed_Char_t
#define substrait_Parameterized_Type_t_kind_varchar_MSGTYPE substrait_Parameterized_Type_Parameterized_Var_Char_t
#define substrait_Parameterized_Type_t_kind_fixed_binary_MSGTYPE substrait_Parameterized_Type_Parameterized_Fixed_Binary_t
#define substrait_Parameterized_Type_t_kind_decimal_MSGTYPE substrait_Parameterized_Type_Parameterized_Decimal_t
#define substrait_Parameterized_Type_t_kind_struct__MSGTYPE substrait_Parameterized_Type_Parameterized_Struct_t
#define substrait_Parameterized_Type_t_kind_list_MSGTYPE substrait_Parameterized_Type_Parameterized_List_t
#define substrait_Parameterized_Type_t_kind_map_MSGTYPE substrait_Parameterized_Type_Parameterized_Map_t
#define substrait_Parameterized_Type_t_kind_timestamp_tz_MSGTYPE substrait_Type_Timestamp_TZ_t
#define substrait_Parameterized_Type_t_kind_user_defined_MSGTYPE substrait_Parameterized_Type_Parameterized_User_Defined_t
#define substrait_Parameterized_Type_t_kind_uuid_MSGTYPE substrait_Type_UUID_t
#define substrait_Parameterized_Type_t_kind_type_parameter_MSGTYPE substrait_Parameterized_Type_Type_Parameter_t
#define substrait_Parameterized_Type_t_kind_precision_timestamp_MSGTYPE substrait_Parameterized_Type_Parameterized_Precision_Timestamp_t
#define substrait_Parameterized_Type_t_kind_precision_timestamp_tz_MSGTYPE substrait_Parameterized_Type_Parameterized_Precision_Timestamp_TZ_t
#define substrait_Parameterized_Type_t_kind_interval_compound_MSGTYPE substrait_Parameterized_Type_Parameterized_Interval_Compound_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  bounds,            2)
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_CALLBACK pb_default_field_callback
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_DEFAULT NULL
#define substrait_Parameterized_Type_Type_Parameter_t_bounds_MSGTYPE substrait_Parameterized_Type_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  range_start_inclusive,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  range_end_exclusive,   3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_CALLBACK pb_default_field_callback
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_DEFAULT NULL
#define substrait_Parameterized_Type_Integer_Parameter_t_range_start_inclusive_MSGTYPE substrait_Parameterized_Type_Nullable_Integer_t
#define substrait_Parameterized_Type_Integer_Parameter_t_range_end_exclusive_MSGTYPE substrait_Parameterized_Type_Nullable_Integer_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    value,             1)
#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_DEFAULT NULL

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  length,            1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Fixed_Char_t_length_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  length,            1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Var_Char_t_length_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  length,            1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Fixed_Binary_t_length_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scale,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  precision,         2) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   3) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       4)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Decimal_t_scale_MSGTYPE substrait_Parameterized_Type_Integer_Option_t
#define substrait_Parameterized_Type_Parameterized_Decimal_t_precision_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  precision,         1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Interval_Day_t_precision_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  precision,         1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Interval_Compound_t_precision_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  precision,         1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Precision_Timestamp_t_precision_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  precision,         1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Precision_Timestamp_TZ_t_precision_MSGTYPE substrait_Parameterized_Type_Integer_Option_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  types,             1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Struct_t_types_MSGTYPE substrait_Parameterized_Type_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   names,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  struct_,           2)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Named_Struct_t_struct__MSGTYPE substrait_Parameterized_Type_Parameterized_Struct_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  type,              1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_CALLBACK pb_default_field_callback
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_List_t_type_MSGTYPE substrait_Parameterized_Type_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  key,               1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  value,             2) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   3) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       4)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_CALLBACK pb_default_field_callback
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_DEFAULT NULL
#define substrait_Parameterized_Type_Parameterized_Map_t_key_MSGTYPE substrait_Parameterized_Type_t
#define substrait_Parameterized_Type_Parameterized_Map_t_value_MSGTYPE substrait_Parameterized_Type_t

#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_pointer,      1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_DEFAULT NULL

#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    INT32,    (integer_type,literal,integer_type.literal),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (integer_type,parameter,integer_type.parameter),   2)
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_CALLBACK NULL
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_DEFAULT NULL
#define substrait_Parameterized_Type_Integer_Option_t_integer_type_parameter_MSGTYPE substrait_Parameterized_Type_Integer_Parameter_t

extern const pb_msgdesc_t substrait_Parameterized_Type_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Type_Parameter_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Integer_Parameter_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Nullable_Integer_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Fixed_Char_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Var_Char_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Fixed_Binary_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Decimal_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Interval_Day_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Interval_Compound_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Precision_Timestamp_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Precision_Timestamp_TZ_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Struct_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Named_Struct_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_List_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_Map_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Parameterized_User_Defined_t_msg;
extern const pb_msgdesc_t substrait_Parameterized_Type_Integer_Option_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_PARAMETERIZED_TYPE_FIELDS &substrait_Parameterized_Type_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_TYPE_PARAMETER_FIELDS &substrait_Parameterized_Type_Type_Parameter_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_PARAMETER_FIELDS &substrait_Parameterized_Type_Integer_Parameter_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_FIELDS &substrait_Parameterized_Type_Nullable_Integer_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_CHAR_FIELDS &substrait_Parameterized_Type_Parameterized_Fixed_Char_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_VAR_CHAR_FIELDS &substrait_Parameterized_Type_Parameterized_Var_Char_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_FIXED_BINARY_FIELDS &substrait_Parameterized_Type_Parameterized_Fixed_Binary_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_DECIMAL_FIELDS &substrait_Parameterized_Type_Parameterized_Decimal_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_DAY_FIELDS &substrait_Parameterized_Type_Parameterized_Interval_Day_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_INTERVAL_COMPOUND_FIELDS &substrait_Parameterized_Type_Parameterized_Interval_Compound_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_FIELDS &substrait_Parameterized_Type_Parameterized_Precision_Timestamp_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_PRECISION_TIMESTAMP_TZ_FIELDS &substrait_Parameterized_Type_Parameterized_Precision_Timestamp_TZ_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_STRUCT_FIELDS &substrait_Parameterized_Type_Parameterized_Struct_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_NAMED_STRUCT_FIELDS &substrait_Parameterized_Type_Parameterized_Named_Struct_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_LIST_FIELDS &substrait_Parameterized_Type_Parameterized_List_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_MAP_FIELDS &substrait_Parameterized_Type_Parameterized_Map_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_FIELDS &substrait_Parameterized_Type_Parameterized_User_Defined_t_msg
#define SUBSTRAIT_PARAMETERIZED_TYPE_INTEGER_OPTION_FIELDS &substrait_Parameterized_Type_Integer_Option_t_msg

/* Maximum encoded size of messages (where known) */
/* substrait_ParameterizedType_size depends on runtime parameters */
/* substrait_ParameterizedType_TypeParameter_size depends on runtime parameters */
/* substrait_ParameterizedType_IntegerParameter_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedFixedChar_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedVarChar_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedFixedBinary_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedDecimal_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedIntervalDay_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedIntervalCompound_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedPrecisionTimestamp_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedPrecisionTimestampTZ_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedStruct_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedNamedStruct_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedList_size depends on runtime parameters */
/* substrait_ParameterizedType_ParameterizedMap_size depends on runtime parameters */
/* substrait_ParameterizedType_IntegerOption_size depends on runtime parameters */
#define SUBSTRAIT_PARAMETERIZED_TYPE_NULLABLE_INTEGER_SIZE 11
#define SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_SIZE 14
#define SUBSTRAIT_SUBSTRAIT_PARAMETERIZED_TYPES_PB_H_MAX_SIZE SUBSTRAIT_PARAMETERIZED_TYPE_PARAMETERIZED_USER_DEFINED_SIZE

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
