/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "substrait/plan.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SUBSTRAIT_PLAN_REL, substrait_Plan_Rel_t, AUTO)


PB_BIND(SUBSTRAIT_PLAN, substrait_Plan_t, AUTO)


PB_BIND(SUBSTRAIT_PLAN_VERSION, substrait_Plan_Version_t, AUTO)


PB_BIND(SUBSTRAIT_VERSION, substrait_Version_t, AUTO)


PB_BIND(SUBSTRAIT_DYNAMIC_PARAMETER_BINDING, substrait_Dynamic_Parameter_Binding_t, AUTO)



