/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_PLAN_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_PLAN_PB_H_INCLUDED
#include <pb.h>
#include "substrait/algebra.pb.h"
#include "substrait/extensions/extensions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Either a relation or root relation */
typedef struct substrait_Plan_Rel {
    pb_size_t which_rel_type;
    union substrait_Plan_Rel_rel_type {
        /* Any relation (used for references and CTEs) */
        substrait_Rel_t rel;
        /* The root of a relation tree */
        substrait_Rel_Root_t root;
    } rel_type;
} substrait_Plan_Rel_t;

typedef struct substrait_Version {
    /* Substrait version number. */
    uint32_t major_number;
    uint32_t minor_number;
    uint32_t patch_number;
    /* If a particular version of Substrait is used that does not correspond to
 a version number exactly (for example when using an unofficial fork or
 using a version that is not yet released or is between versions), set this
 to the full git hash of the utilized commit of
 https://github.com/substrait-io/substrait (or fork thereof), represented
 using a lowercase hex ASCII string 40 characters in length. The version
 number above should be set to the most recent version tag in the history
 of that commit. */
    pb_callback_t git_hash;
    /* Identifying information for the producer that created this plan. Under
 ideal circumstances, consumers should not need this information. However,
 it is foreseen that consumers may need to work around bugs in particular
 producers in practice, and therefore may need to know which producer
 created the plan. */
    pb_callback_t producer;
} substrait_Version_t;

/* Describe a set of operations to complete.
 For compactness sake, identifiers are normalized at the plan level. */
typedef struct substrait_Plan {
    /* a list of yaml specifications this plan may depend on */
    pb_callback_t extension_uris;
    /* a list of extensions this plan may depend on */
    pb_callback_t extensions;
    /* one or more relation trees that are associated with this plan. */
    pb_callback_t relations;
    /* additional extensions associated with this plan. */
    bool has_advanced_extensions;
    substrait_extensions_Advanced_Extension_t advanced_extensions;
    /* A list of com.google.Any entities that this plan may use. Can be used to
 warn if some embedded message types are unknown. Note that this list may
 include message types that are ignorable (optimizations) or that are
 unused. In many cases, a consumer may be able to work with a plan even if
 one or more message types defined here are unknown. */
    pb_callback_t expected_type_urls;
    /* Substrait version of the plan. Optional up to 0.17.0, required for later
 versions. */
    bool has_version;
    substrait_Version_t version;
    /* An optional list of bindings for dynamic parameters used in this plan.
 Each binding maps a parameter_anchor to its corresponding runtime value. */
    pb_callback_t parameter_bindings;
} substrait_Plan_t;

/* This message type can be used to deserialize only the version of a Substrait
 Plan message. This prevents deserialization errors when there were breaking
 changes between the Substrait version of the tool that produced the plan and
 the Substrait version used to deserialize it, such that a consumer can emit
 a more helpful error message in this case. */
typedef struct substrait_Plan_Version {
    bool has_version;
    substrait_Version_t version;
} substrait_Plan_Version_t;

/* Represents a binding for a dynamic parameter. */
typedef struct substrait_Dynamic_Parameter_Binding {
    /* The parameter anchor that identifies the dynamic parameter reference. */
    uint32_t parameter_anchor;
    /* The literal value assigned to the parameter at runtime.
 The type of the literal needs to match the type of the corresponding
 DynamicParameter expression in the plan. */
    bool has_value;
    substrait_Expression_Literal_t value;
} substrait_Dynamic_Parameter_Binding_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SUBSTRAIT_PLAN_REL_INIT_DEFAULT          {0, {SUBSTRAIT_REL_INIT_DEFAULT}}
#define SUBSTRAIT_PLAN_INIT_DEFAULT              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_INIT_DEFAULT, {{NULL}, NULL}, false, SUBSTRAIT_VERSION_INIT_DEFAULT, {{NULL}, NULL}}
#define SUBSTRAIT_PLAN_VERSION_INIT_DEFAULT      {false, SUBSTRAIT_VERSION_INIT_DEFAULT}
#define SUBSTRAIT_VERSION_INIT_DEFAULT           {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_INIT_DEFAULT {0, false, SUBSTRAIT_EXPRESSION_LITERAL_INIT_DEFAULT}
#define SUBSTRAIT_PLAN_REL_INIT_ZERO             {0, {SUBSTRAIT_REL_INIT_ZERO}}
#define SUBSTRAIT_PLAN_INIT_ZERO                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, SUBSTRAIT_EXTENSIONS_ADVANCED_EXTENSION_INIT_ZERO, {{NULL}, NULL}, false, SUBSTRAIT_VERSION_INIT_ZERO, {{NULL}, NULL}}
#define SUBSTRAIT_PLAN_VERSION_INIT_ZERO         {false, SUBSTRAIT_VERSION_INIT_ZERO}
#define SUBSTRAIT_VERSION_INIT_ZERO              {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_INIT_ZERO {0, false, SUBSTRAIT_EXPRESSION_LITERAL_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_PLAN_REL_REL_TAG               1
#define SUBSTRAIT_PLAN_REL_ROOT_TAG              2
#define SUBSTRAIT_VERSION_MAJOR_NUMBER_TAG       1
#define SUBSTRAIT_VERSION_MINOR_NUMBER_TAG       2
#define SUBSTRAIT_VERSION_PATCH_NUMBER_TAG       3
#define SUBSTRAIT_VERSION_GIT_HASH_TAG           4
#define SUBSTRAIT_VERSION_PRODUCER_TAG           5
#define SUBSTRAIT_PLAN_EXTENSION_URIS_TAG        1
#define SUBSTRAIT_PLAN_EXTENSIONS_TAG            2
#define SUBSTRAIT_PLAN_RELATIONS_TAG             3
#define SUBSTRAIT_PLAN_ADVANCED_EXTENSIONS_TAG   4
#define SUBSTRAIT_PLAN_EXPECTED_TYPE_URLS_TAG    5
#define SUBSTRAIT_PLAN_VERSION_TAG               6
#define SUBSTRAIT_PLAN_PARAMETER_BINDINGS_TAG    7
#define SUBSTRAIT_PLAN_VERSION_VERSION_TAG       6
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_PARAMETER_ANCHOR_TAG 1
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_VALUE_TAG 2

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_PLAN_REL_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rel_type,rel,rel_type.rel),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rel_type,root,rel_type.root),   2)
#define SUBSTRAIT_PLAN_REL_CALLBACK NULL
#define SUBSTRAIT_PLAN_REL_DEFAULT NULL
#define substrait_Plan_Rel_t_rel_type_rel_MSGTYPE substrait_Rel_t
#define substrait_Plan_Rel_t_rel_type_root_MSGTYPE substrait_Rel_Root_t

#define SUBSTRAIT_PLAN_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  extension_uris,    1) \
X(a, CALLBACK, REPEATED, MESSAGE,  extensions,        2) \
X(a, CALLBACK, REPEATED, MESSAGE,  relations,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  advanced_extensions,   4) \
X(a, CALLBACK, REPEATED, STRING,   expected_type_urls,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           6) \
X(a, CALLBACK, REPEATED, MESSAGE,  parameter_bindings,   7)
#define SUBSTRAIT_PLAN_CALLBACK pb_default_field_callback
#define SUBSTRAIT_PLAN_DEFAULT NULL
#define substrait_Plan_t_extension_uris_MSGTYPE substrait_extensions_Simple_Extension_URI_t
#define substrait_Plan_t_extensions_MSGTYPE substrait_extensions_Simple_Extension_Declaration_t
#define substrait_Plan_t_relations_MSGTYPE substrait_Plan_Rel_t
#define substrait_Plan_t_advanced_extensions_MSGTYPE substrait_extensions_Advanced_Extension_t
#define substrait_Plan_t_version_MSGTYPE substrait_Version_t
#define substrait_Plan_t_parameter_bindings_MSGTYPE substrait_Dynamic_Parameter_Binding_t

#define SUBSTRAIT_PLAN_VERSION_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           6)
#define SUBSTRAIT_PLAN_VERSION_CALLBACK NULL
#define SUBSTRAIT_PLAN_VERSION_DEFAULT NULL
#define substrait_Plan_Version_t_version_MSGTYPE substrait_Version_t

#define SUBSTRAIT_VERSION_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major_number,      1) \
X(a, STATIC,   SINGULAR, UINT32,   minor_number,      2) \
X(a, STATIC,   SINGULAR, UINT32,   patch_number,      3) \
X(a, CALLBACK, SINGULAR, STRING,   git_hash,          4) \
X(a, CALLBACK, SINGULAR, STRING,   producer,          5)
#define SUBSTRAIT_VERSION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_VERSION_DEFAULT NULL

#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   parameter_anchor,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_CALLBACK NULL
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_DEFAULT NULL
#define substrait_Dynamic_Parameter_Binding_t_value_MSGTYPE substrait_Expression_Literal_t

extern const pb_msgdesc_t substrait_Plan_Rel_t_msg;
extern const pb_msgdesc_t substrait_Plan_t_msg;
extern const pb_msgdesc_t substrait_Plan_Version_t_msg;
extern const pb_msgdesc_t substrait_Version_t_msg;
extern const pb_msgdesc_t substrait_Dynamic_Parameter_Binding_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_PLAN_REL_FIELDS &substrait_Plan_Rel_t_msg
#define SUBSTRAIT_PLAN_FIELDS &substrait_Plan_t_msg
#define SUBSTRAIT_PLAN_VERSION_FIELDS &substrait_Plan_Version_t_msg
#define SUBSTRAIT_VERSION_FIELDS &substrait_Version_t_msg
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_FIELDS &substrait_Dynamic_Parameter_Binding_t_msg

/* Maximum encoded size of messages (where known) */
#if defined(substrait_Rel_size) && defined(substrait_RelRoot_size)
union substrait_PlanRel_rel_type_size_union {char f1[(6 + substrait_Rel_size)]; char f2[(6 + substrait_RelRoot_size)];};
#endif
/* substrait_Plan_size depends on runtime parameters */
/* substrait_PlanVersion_size depends on runtime parameters */
/* substrait_Version_size depends on runtime parameters */
#if defined(substrait_Rel_size) && defined(substrait_RelRoot_size)
#define SUBSTRAIT_PLAN_REL_SIZE                  (0 + sizeof(union substrait_PlanRel_rel_type_size_union))
#endif
#if defined(substrait_Expression_Literal_size)
#define SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_SIZE (12 + substrait_Expression_Literal_size)
#define SUBSTRAIT_SUBSTRAIT_PLAN_PB_H_MAX_SIZE   SUBSTRAIT_DYNAMIC_PARAMETER_BINDING_SIZE
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
