/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_TYPE_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_TYPE_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/empty.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum substrait_Type_Nullability {
    SUBSTRAIT_TYPE_NULLABILITY_NULLABILITY_UNSPECIFIED = 0,
    SUBSTRAIT_TYPE_NULLABILITY_NULLABILITY_NULLABLE = 1,
    SUBSTRAIT_TYPE_NULLABILITY_NULLABILITY_REQUIRED = 2
} substrait_Type_Nullability_t;

/* Struct definitions */
typedef struct substrait_Type_Boolean {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Boolean_t;

typedef struct substrait_Type_I8 {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_I8_t;

typedef struct substrait_Type_I16 {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_I16_t;

typedef struct substrait_Type_I32 {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_I32_t;

typedef struct substrait_Type_I64 {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_I64_t;

typedef struct substrait_Type_FP32 {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_FP32_t;

typedef struct substrait_Type_FP64 {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_FP64_t;

typedef struct substrait_Type_String {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_String_t;

typedef struct substrait_Type_Binary {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Binary_t;

typedef struct substrait_Type_Timestamp {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Timestamp_t;

typedef struct substrait_Type_Date {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Date_t;

typedef struct substrait_Type_Time {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Time_t;

typedef struct substrait_Type_Timestamp_TZ {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Timestamp_TZ_t;

/* An interval consisting of years and months */
typedef struct substrait_Type_Interval_Year {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Interval_Year_t;

/* An interval consisting of days, seconds, and microseconds */
typedef struct substrait_Type_Interval_Day {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
    /* Sub-second precision, 0 means the value given is in seconds, 3 is milliseconds, 6 microseconds, 9 is nanoseconds, etc.
 if unset, treat as 6. */
    bool has_precision;
    int32_t precision;
} substrait_Type_Interval_Day_t;

/* An interval consisting of the components of both IntervalMonth and IntervalDay */
typedef struct substrait_Type_Interval_Compound {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
    /* Sub-second precision, 0 means the value given is in seconds, 3 is milliseconds, 6 microseconds, 9 is nanoseconds, etc. */
    int32_t precision;
} substrait_Type_Interval_Compound_t;

typedef struct substrait_Type_UUID {
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_UUID_t;

/* Start compound types. */
typedef struct substrait_Type_Fixed_Char {
    int32_t length;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Fixed_Char_t;

typedef struct substrait_Type_Var_Char {
    int32_t length;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Var_Char_t;

typedef struct substrait_Type_Fixed_Binary {
    int32_t length;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Fixed_Binary_t;

typedef struct substrait_Type_Decimal {
    int32_t scale;
    int32_t precision;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Decimal_t;

typedef struct substrait_Type_Precision_Timestamp {
    /* Sub-second precision, 0 means the value given is in seconds, 3 is milliseconds, 6 microseconds, 9 is nanoseconds, 12 is picoseconds */
    int32_t precision;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Precision_Timestamp_t;

typedef struct substrait_Type_Precision_Timestamp_TZ {
    /* Sub-second precision, 0 means the value given is in seconds, 3 is milliseconds, 6 microseconds, 9 is nanoseconds, 12 is picoseconds */
    int32_t precision;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Precision_Timestamp_TZ_t;

typedef struct substrait_Type_Struct {
    pb_callback_t types;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
} substrait_Type_Struct_t;

typedef struct substrait_Type_List {
    pb_callback_t type;
    pb_callback_t type_variation_reference;
    pb_callback_t nullability;
} substrait_Type_List_t;

typedef struct substrait_Type_Map {
    pb_callback_t key;
    pb_callback_t value;
    pb_callback_t type_variation_reference;
    pb_callback_t nullability;
} substrait_Type_Map_t;

typedef struct substrait_Type_User_Defined {
    uint32_t type_reference;
    uint32_t type_variation_reference;
    substrait_Type_Nullability_t nullability;
    pb_callback_t type_parameters;
} substrait_Type_User_Defined_t;

typedef struct substrait_Type {
    pb_size_t which_kind;
    union substrait_Type_kind {
        substrait_Type_Boolean_t bool_;
        substrait_Type_I8_t i8;
        substrait_Type_I16_t i16;
        substrait_Type_I32_t i32;
        substrait_Type_I64_t i64;
        substrait_Type_FP32_t fp32;
        substrait_Type_FP64_t fp64;
        substrait_Type_String_t string;
        substrait_Type_Binary_t binary;
        /* Deprecated in favor of `PrecisionTimestamp precision_timestamp` */
        substrait_Type_Timestamp_t timestamp;
        substrait_Type_Date_t date;
        substrait_Type_Time_t time;
        substrait_Type_Interval_Year_t interval_year;
        substrait_Type_Interval_Day_t interval_day;
        substrait_Type_Fixed_Char_t fixed_char;
        substrait_Type_Var_Char_t varchar;
        substrait_Type_Fixed_Binary_t fixed_binary;
        substrait_Type_Decimal_t decimal;
        substrait_Type_Struct_t struct_;
        substrait_Type_List_t list;
        substrait_Type_Map_t map;
        /* Deprecated in favor of `PrecisionTimestampTZ precision_timestamp_tz` */
        substrait_Type_Timestamp_TZ_t timestamp_tz;
        substrait_Type_User_Defined_t user_defined;
        /* Deprecated in favor of user_defined, which allows nullability and
     variations to be specified. If user_defined_type_reference is
     encountered, treat it as being non-nullable and having the default
     variation. */
        uint32_t user_defined_type_reference;
        substrait_Type_UUID_t uuid;
        substrait_Type_Precision_Timestamp_t precision_timestamp;
        substrait_Type_Precision_Timestamp_TZ_t precision_timestamp_tz; /* value is since UNIX epoch in UTC */
        substrait_Type_Interval_Compound_t interval_compound;
    } kind;
} substrait_Type_t;

typedef struct substrait_Type_Parameter {
    pb_size_t which_parameter;
    union substrait_Type_Parameter_parameter {
        /* Explicitly null/unspecified parameter, to select the default value (if
     any). */
        google_protobuf_Empty_t null;
        /* Data type parameters, like the i32 in LIST<i32>. */
        substrait_Type_t data_type;
        /* Value parameters, like the 10 in VARCHAR<10>. */
        bool boolean;
        int64_t integer;
        pb_callback_t enum_;
        pb_callback_t string;
    } parameter;
} substrait_Type_Parameter_t;

/* A message for modeling name/type pairs.

 Useful for representing relation schemas.

 Notes:

 * The names field is in depth-first order.

 For example a schema such as:

 a: int64
 b: struct<c: float32, d: string>

 would have a `names` field that looks like:

 ["a", "b", "c", "d"]

 * Only struct fields are contained in this field's elements,
 * Map keys should be traversed first, then values when producing/consuming */
typedef struct substrait_Named_Struct {
    /* list of names in dfs order */
    pb_callback_t names;
    bool has_struct_;
    substrait_Type_Struct_t struct_;
} substrait_Named_Struct_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SUBSTRAIT_TYPE_NULLABILITY_MIN SUBSTRAIT_TYPE_NULLABILITY_NULLABILITY_UNSPECIFIED
#define _SUBSTRAIT_TYPE_NULLABILITY_MAX SUBSTRAIT_TYPE_NULLABILITY_NULLABILITY_REQUIRED
#define _SUBSTRAIT_TYPE_NULLABILITY_ARRAYSIZE ((substrait_Type_Nullability_t)(SUBSTRAIT_TYPE_NULLABILITY_NULLABILITY_REQUIRED+1))


#define substrait_Type_Boolean_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_I8_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_I16_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_I32_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_I64_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_FP32_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_FP64_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_String_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Binary_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Timestamp_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Date_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Time_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Timestamp_TZ_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Interval_Year_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Interval_Day_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Interval_Compound_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_UUID_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Fixed_Char_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Var_Char_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Fixed_Binary_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Decimal_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Precision_Timestamp_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Precision_Timestamp_TZ_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Struct_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_List_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_Map_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Type_User_Defined_t_nullability_ENUMTYPE substrait_Type_Nullability_t




/* Initializer values for message structs */
#define SUBSTRAIT_TYPE_INIT_DEFAULT              {0, {SUBSTRAIT_TYPE_BOOLEAN_INIT_DEFAULT}}
#define SUBSTRAIT_TYPE_BOOLEAN_INIT_DEFAULT      {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I8_INIT_DEFAULT           {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I16_INIT_DEFAULT          {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I32_INIT_DEFAULT          {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I64_INIT_DEFAULT          {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FP32_INIT_DEFAULT         {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FP64_INIT_DEFAULT         {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_STRING_INIT_DEFAULT       {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_BINARY_INIT_DEFAULT       {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_TIMESTAMP_INIT_DEFAULT    {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_DATE_INIT_DEFAULT         {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_TIME_INIT_DEFAULT         {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_INIT_DEFAULT {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_INIT_DEFAULT {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_INTERVAL_DAY_INIT_DEFAULT {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN, false, 0}
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_INIT_DEFAULT {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN, 0}
#define SUBSTRAIT_TYPE_UUID_INIT_DEFAULT         {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FIXED_CHAR_INIT_DEFAULT   {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_VAR_CHAR_INIT_DEFAULT     {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FIXED_BINARY_INIT_DEFAULT {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_DECIMAL_INIT_DEFAULT      {0, 0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_INIT_DEFAULT {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_INIT_DEFAULT {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_STRUCT_INIT_DEFAULT       {{{NULL}, NULL}, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_LIST_INIT_DEFAULT         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_TYPE_MAP_INIT_DEFAULT          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_TYPE_USER_DEFINED_INIT_DEFAULT {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN, {{NULL}, NULL}}
#define SUBSTRAIT_TYPE_PARAMETER_INIT_DEFAULT    {0, {GOOGLE_PROTOBUF_EMPTY_INIT_DEFAULT}}
#define SUBSTRAIT_NAMED_STRUCT_INIT_DEFAULT      {{{NULL}, NULL}, false, SUBSTRAIT_TYPE_STRUCT_INIT_DEFAULT}
#define SUBSTRAIT_TYPE_INIT_ZERO                 {0, {SUBSTRAIT_TYPE_BOOLEAN_INIT_ZERO}}
#define SUBSTRAIT_TYPE_BOOLEAN_INIT_ZERO         {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I8_INIT_ZERO              {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I16_INIT_ZERO             {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I32_INIT_ZERO             {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_I64_INIT_ZERO             {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FP32_INIT_ZERO            {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FP64_INIT_ZERO            {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_STRING_INIT_ZERO          {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_BINARY_INIT_ZERO          {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_TIMESTAMP_INIT_ZERO       {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_DATE_INIT_ZERO            {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_TIME_INIT_ZERO            {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_INIT_ZERO    {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_INIT_ZERO   {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_INTERVAL_DAY_INIT_ZERO    {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN, false, 0}
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_INIT_ZERO {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN, 0}
#define SUBSTRAIT_TYPE_UUID_INIT_ZERO            {0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FIXED_CHAR_INIT_ZERO      {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_VAR_CHAR_INIT_ZERO        {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_FIXED_BINARY_INIT_ZERO    {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_DECIMAL_INIT_ZERO         {0, 0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_INIT_ZERO {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_INIT_ZERO {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_STRUCT_INIT_ZERO          {{{NULL}, NULL}, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_TYPE_LIST_INIT_ZERO            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_TYPE_MAP_INIT_ZERO             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_TYPE_USER_DEFINED_INIT_ZERO    {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN, {{NULL}, NULL}}
#define SUBSTRAIT_TYPE_PARAMETER_INIT_ZERO       {0, {GOOGLE_PROTOBUF_EMPTY_INIT_ZERO}}
#define SUBSTRAIT_NAMED_STRUCT_INIT_ZERO         {{{NULL}, NULL}, false, SUBSTRAIT_TYPE_STRUCT_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_TYPE_BOOLEAN_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_BOOLEAN_NULLABILITY_TAG   2
#define SUBSTRAIT_TYPE_I8_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_I8_NULLABILITY_TAG        2
#define SUBSTRAIT_TYPE_I16_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_I16_NULLABILITY_TAG       2
#define SUBSTRAIT_TYPE_I32_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_I32_NULLABILITY_TAG       2
#define SUBSTRAIT_TYPE_I64_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_I64_NULLABILITY_TAG       2
#define SUBSTRAIT_TYPE_FP32_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_FP32_NULLABILITY_TAG      2
#define SUBSTRAIT_TYPE_FP64_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_FP64_NULLABILITY_TAG      2
#define SUBSTRAIT_TYPE_STRING_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_STRING_NULLABILITY_TAG    2
#define SUBSTRAIT_TYPE_BINARY_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_BINARY_NULLABILITY_TAG    2
#define SUBSTRAIT_TYPE_TIMESTAMP_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_TIMESTAMP_NULLABILITY_TAG 2
#define SUBSTRAIT_TYPE_DATE_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_DATE_NULLABILITY_TAG      2
#define SUBSTRAIT_TYPE_TIME_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_TIME_NULLABILITY_TAG      2
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_NULLABILITY_TAG 2
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_NULLABILITY_TAG 2
#define SUBSTRAIT_TYPE_INTERVAL_DAY_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_INTERVAL_DAY_NULLABILITY_TAG 2
#define SUBSTRAIT_TYPE_INTERVAL_DAY_PRECISION_TAG 3
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_NULLABILITY_TAG 2
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_PRECISION_TAG 3
#define SUBSTRAIT_TYPE_UUID_TYPE_VARIATION_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_UUID_NULLABILITY_TAG      2
#define SUBSTRAIT_TYPE_FIXED_CHAR_LENGTH_TAG     1
#define SUBSTRAIT_TYPE_FIXED_CHAR_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_FIXED_CHAR_NULLABILITY_TAG 3
#define SUBSTRAIT_TYPE_VAR_CHAR_LENGTH_TAG       1
#define SUBSTRAIT_TYPE_VAR_CHAR_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_VAR_CHAR_NULLABILITY_TAG  3
#define SUBSTRAIT_TYPE_FIXED_BINARY_LENGTH_TAG   1
#define SUBSTRAIT_TYPE_FIXED_BINARY_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_FIXED_BINARY_NULLABILITY_TAG 3
#define SUBSTRAIT_TYPE_DECIMAL_SCALE_TAG         1
#define SUBSTRAIT_TYPE_DECIMAL_PRECISION_TAG     2
#define SUBSTRAIT_TYPE_DECIMAL_TYPE_VARIATION_REFERENCE_TAG 3
#define SUBSTRAIT_TYPE_DECIMAL_NULLABILITY_TAG   4
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_PRECISION_TAG 1
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_NULLABILITY_TAG 3
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_PRECISION_TAG 1
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_NULLABILITY_TAG 3
#define SUBSTRAIT_TYPE_STRUCT_TYPES_TAG          1
#define SUBSTRAIT_TYPE_STRUCT_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_STRUCT_NULLABILITY_TAG    3
#define SUBSTRAIT_TYPE_LIST_TYPE_TAG             1
#define SUBSTRAIT_TYPE_LIST_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_LIST_NULLABILITY_TAG      3
#define SUBSTRAIT_TYPE_MAP_KEY_TAG               1
#define SUBSTRAIT_TYPE_MAP_VALUE_TAG             2
#define SUBSTRAIT_TYPE_MAP_TYPE_VARIATION_REFERENCE_TAG 3
#define SUBSTRAIT_TYPE_MAP_NULLABILITY_TAG       4
#define SUBSTRAIT_TYPE_USER_DEFINED_TYPE_REFERENCE_TAG 1
#define SUBSTRAIT_TYPE_USER_DEFINED_TYPE_VARIATION_REFERENCE_TAG 2
#define SUBSTRAIT_TYPE_USER_DEFINED_NULLABILITY_TAG 3
#define SUBSTRAIT_TYPE_USER_DEFINED_TYPE_PARAMETERS_TAG 4
#define SUBSTRAIT_TYPE_BOOL_TAG                  1
#define SUBSTRAIT_TYPE_I8_TAG                    2
#define SUBSTRAIT_TYPE_I16_TAG                   3
#define SUBSTRAIT_TYPE_I32_TAG                   5
#define SUBSTRAIT_TYPE_I64_TAG                   7
#define SUBSTRAIT_TYPE_FP32_TAG                  10
#define SUBSTRAIT_TYPE_FP64_TAG                  11
#define SUBSTRAIT_TYPE_STRING_TAG                12
#define SUBSTRAIT_TYPE_BINARY_TAG                13
#define SUBSTRAIT_TYPE_TIMESTAMP_TAG             14
#define SUBSTRAIT_TYPE_DATE_TAG                  16
#define SUBSTRAIT_TYPE_TIME_TAG                  17
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_TAG         19
#define SUBSTRAIT_TYPE_INTERVAL_DAY_TAG          20
#define SUBSTRAIT_TYPE_FIXED_CHAR_TAG            21
#define SUBSTRAIT_TYPE_VARCHAR_TAG               22
#define SUBSTRAIT_TYPE_FIXED_BINARY_TAG          23
#define SUBSTRAIT_TYPE_DECIMAL_TAG               24
#define SUBSTRAIT_TYPE_STRUCT_TAG                25
#define SUBSTRAIT_TYPE_LIST_TAG                  27
#define SUBSTRAIT_TYPE_MAP_TAG                   28
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_TAG          29
#define SUBSTRAIT_TYPE_USER_DEFINED_TAG          30
#define SUBSTRAIT_TYPE_USER_DEFINED_TYPE_REFERENCE_TAG 31
#define SUBSTRAIT_TYPE_UUID_TAG                  32
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TAG   33
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_TAG 34
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_TAG     35
#define SUBSTRAIT_TYPE_PARAMETER_NULL_TAG        1
#define SUBSTRAIT_TYPE_PARAMETER_DATA_TYPE_TAG   2
#define SUBSTRAIT_TYPE_PARAMETER_BOOLEAN_TAG     3
#define SUBSTRAIT_TYPE_PARAMETER_INTEGER_TAG     4
#define SUBSTRAIT_TYPE_PARAMETER_ENUM_TAG        5
#define SUBSTRAIT_TYPE_PARAMETER_STRING_TAG      6
#define SUBSTRAIT_NAMED_STRUCT_NAMES_TAG         1
#define SUBSTRAIT_NAMED_STRUCT_STRUCT_TAG        2

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_TYPE_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,bool_,kind.bool_),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i8,kind.i8),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i16,kind.i16),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i32,kind.i32),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i64,kind.i64),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fp32,kind.fp32),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fp64,kind.fp64),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,string,kind.string),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,binary,kind.binary),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,timestamp,kind.timestamp),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,date,kind.date),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,time,kind.time),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_year,kind.interval_year),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_day,kind.interval_day),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fixed_char,kind.fixed_char),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,varchar,kind.varchar),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fixed_binary,kind.fixed_binary),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,decimal,kind.decimal),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,struct_,kind.struct_),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,list,kind.list),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,map,kind.map),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,timestamp_tz,kind.timestamp_tz),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,user_defined,kind.user_defined),  30) \
X(a, STATIC,   ONEOF,    UINT32,   (kind,user_defined_type_reference,kind.user_defined_type_reference),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,uuid,kind.uuid),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,precision_timestamp,kind.precision_timestamp),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,precision_timestamp_tz,kind.precision_timestamp_tz),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_compound,kind.interval_compound),  35)
#define SUBSTRAIT_TYPE_CALLBACK NULL
#define SUBSTRAIT_TYPE_DEFAULT NULL
#define substrait_Type_t_kind_bool__MSGTYPE substrait_Type_Boolean_t
#define substrait_Type_t_kind_i8_MSGTYPE substrait_Type_I8_t
#define substrait_Type_t_kind_i16_MSGTYPE substrait_Type_I16_t
#define substrait_Type_t_kind_i32_MSGTYPE substrait_Type_I32_t
#define substrait_Type_t_kind_i64_MSGTYPE substrait_Type_I64_t
#define substrait_Type_t_kind_fp32_MSGTYPE substrait_Type_FP32_t
#define substrait_Type_t_kind_fp64_MSGTYPE substrait_Type_FP64_t
#define substrait_Type_t_kind_string_MSGTYPE substrait_Type_String_t
#define substrait_Type_t_kind_binary_MSGTYPE substrait_Type_Binary_t
#define substrait_Type_t_kind_timestamp_MSGTYPE substrait_Type_Timestamp_t
#define substrait_Type_t_kind_date_MSGTYPE substrait_Type_Date_t
#define substrait_Type_t_kind_time_MSGTYPE substrait_Type_Time_t
#define substrait_Type_t_kind_interval_year_MSGTYPE substrait_Type_Interval_Year_t
#define substrait_Type_t_kind_interval_day_MSGTYPE substrait_Type_Interval_Day_t
#define substrait_Type_t_kind_fixed_char_MSGTYPE substrait_Type_Fixed_Char_t
#define substrait_Type_t_kind_varchar_MSGTYPE substrait_Type_Var_Char_t
#define substrait_Type_t_kind_fixed_binary_MSGTYPE substrait_Type_Fixed_Binary_t
#define substrait_Type_t_kind_decimal_MSGTYPE substrait_Type_Decimal_t
#define substrait_Type_t_kind_struct__MSGTYPE substrait_Type_Struct_t
#define substrait_Type_t_kind_list_MSGTYPE substrait_Type_List_t
#define substrait_Type_t_kind_map_MSGTYPE substrait_Type_Map_t
#define substrait_Type_t_kind_timestamp_tz_MSGTYPE substrait_Type_Timestamp_TZ_t
#define substrait_Type_t_kind_user_defined_MSGTYPE substrait_Type_User_Defined_t
#define substrait_Type_t_kind_uuid_MSGTYPE substrait_Type_UUID_t
#define substrait_Type_t_kind_precision_timestamp_MSGTYPE substrait_Type_Precision_Timestamp_t
#define substrait_Type_t_kind_precision_timestamp_tz_MSGTYPE substrait_Type_Precision_Timestamp_TZ_t
#define substrait_Type_t_kind_interval_compound_MSGTYPE substrait_Type_Interval_Compound_t

#define SUBSTRAIT_TYPE_BOOLEAN_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_BOOLEAN_CALLBACK NULL
#define SUBSTRAIT_TYPE_BOOLEAN_DEFAULT NULL

#define SUBSTRAIT_TYPE_I8_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_I8_CALLBACK NULL
#define SUBSTRAIT_TYPE_I8_DEFAULT NULL

#define SUBSTRAIT_TYPE_I16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_I16_CALLBACK NULL
#define SUBSTRAIT_TYPE_I16_DEFAULT NULL

#define SUBSTRAIT_TYPE_I32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_I32_CALLBACK NULL
#define SUBSTRAIT_TYPE_I32_DEFAULT NULL

#define SUBSTRAIT_TYPE_I64_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_I64_CALLBACK NULL
#define SUBSTRAIT_TYPE_I64_DEFAULT NULL

#define SUBSTRAIT_TYPE_FP32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_FP32_CALLBACK NULL
#define SUBSTRAIT_TYPE_FP32_DEFAULT NULL

#define SUBSTRAIT_TYPE_FP64_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_FP64_CALLBACK NULL
#define SUBSTRAIT_TYPE_FP64_DEFAULT NULL

#define SUBSTRAIT_TYPE_STRING_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_STRING_CALLBACK NULL
#define SUBSTRAIT_TYPE_STRING_DEFAULT NULL

#define SUBSTRAIT_TYPE_BINARY_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_BINARY_CALLBACK NULL
#define SUBSTRAIT_TYPE_BINARY_DEFAULT NULL

#define SUBSTRAIT_TYPE_TIMESTAMP_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_TIMESTAMP_CALLBACK NULL
#define SUBSTRAIT_TYPE_TIMESTAMP_DEFAULT NULL

#define SUBSTRAIT_TYPE_DATE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_DATE_CALLBACK NULL
#define SUBSTRAIT_TYPE_DATE_DEFAULT NULL

#define SUBSTRAIT_TYPE_TIME_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_TIME_CALLBACK NULL
#define SUBSTRAIT_TYPE_TIME_DEFAULT NULL

#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_CALLBACK NULL
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_DEFAULT NULL

#define SUBSTRAIT_TYPE_INTERVAL_YEAR_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_CALLBACK NULL
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_DEFAULT NULL

#define SUBSTRAIT_TYPE_INTERVAL_DAY_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2) \
X(a, STATIC,   OPTIONAL, INT32,    precision,         3)
#define SUBSTRAIT_TYPE_INTERVAL_DAY_CALLBACK NULL
#define SUBSTRAIT_TYPE_INTERVAL_DAY_DEFAULT NULL

#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2) \
X(a, STATIC,   SINGULAR, INT32,    precision,         3)
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_CALLBACK NULL
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_DEFAULT NULL

#define SUBSTRAIT_TYPE_UUID_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       2)
#define SUBSTRAIT_TYPE_UUID_CALLBACK NULL
#define SUBSTRAIT_TYPE_UUID_DEFAULT NULL

#define SUBSTRAIT_TYPE_FIXED_CHAR_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    length,            1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_TYPE_FIXED_CHAR_CALLBACK NULL
#define SUBSTRAIT_TYPE_FIXED_CHAR_DEFAULT NULL

#define SUBSTRAIT_TYPE_VAR_CHAR_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    length,            1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_TYPE_VAR_CHAR_CALLBACK NULL
#define SUBSTRAIT_TYPE_VAR_CHAR_DEFAULT NULL

#define SUBSTRAIT_TYPE_FIXED_BINARY_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    length,            1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_TYPE_FIXED_BINARY_CALLBACK NULL
#define SUBSTRAIT_TYPE_FIXED_BINARY_DEFAULT NULL

#define SUBSTRAIT_TYPE_DECIMAL_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    scale,             1) \
X(a, STATIC,   SINGULAR, INT32,    precision,         2) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   3) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       4)
#define SUBSTRAIT_TYPE_DECIMAL_CALLBACK NULL
#define SUBSTRAIT_TYPE_DECIMAL_DEFAULT NULL

#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    precision,         1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_CALLBACK NULL
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_DEFAULT NULL

#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    precision,         1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_CALLBACK NULL
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_DEFAULT NULL

#define SUBSTRAIT_TYPE_STRUCT_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  types,             1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_TYPE_STRUCT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_TYPE_STRUCT_DEFAULT NULL
#define substrait_Type_Struct_t_types_MSGTYPE substrait_Type_t

#define SUBSTRAIT_TYPE_LIST_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  type,              1) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_TYPE_LIST_CALLBACK pb_default_field_callback
#define SUBSTRAIT_TYPE_LIST_DEFAULT NULL
#define substrait_Type_List_t_type_MSGTYPE substrait_Type_t

#define SUBSTRAIT_TYPE_MAP_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  key,               1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  value,             2) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   3) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       4)
#define SUBSTRAIT_TYPE_MAP_CALLBACK pb_default_field_callback
#define SUBSTRAIT_TYPE_MAP_DEFAULT NULL
#define substrait_Type_Map_t_key_MSGTYPE substrait_Type_t
#define substrait_Type_Map_t_value_MSGTYPE substrait_Type_t

#define SUBSTRAIT_TYPE_USER_DEFINED_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_reference,    1) \
X(a, STATIC,   SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3) \
X(a, CALLBACK, REPEATED, MESSAGE,  type_parameters,   4)
#define SUBSTRAIT_TYPE_USER_DEFINED_CALLBACK pb_default_field_callback
#define SUBSTRAIT_TYPE_USER_DEFINED_DEFAULT NULL
#define substrait_Type_User_Defined_t_type_parameters_MSGTYPE substrait_Type_Parameter_t

#define SUBSTRAIT_TYPE_PARAMETER_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (parameter,null,parameter.null),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (parameter,data_type,parameter.data_type),   2) \
X(a, STATIC,   ONEOF,    BOOL,     (parameter,boolean,parameter.boolean),   3) \
X(a, STATIC,   ONEOF,    INT64,    (parameter,integer,parameter.integer),   4) \
X(a, CALLBACK, ONEOF,    STRING,   (parameter,enum_,parameter.enum_),   5) \
X(a, CALLBACK, ONEOF,    STRING,   (parameter,string,parameter.string),   6)
#define SUBSTRAIT_TYPE_PARAMETER_CALLBACK pb_default_field_callback
#define SUBSTRAIT_TYPE_PARAMETER_DEFAULT NULL
#define substrait_Type_Parameter_t_parameter_null_MSGTYPE google_protobuf_Empty_t
#define substrait_Type_Parameter_t_parameter_data_type_MSGTYPE substrait_Type_t

#define SUBSTRAIT_NAMED_STRUCT_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   names,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  struct_,           2)
#define SUBSTRAIT_NAMED_STRUCT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_NAMED_STRUCT_DEFAULT NULL
#define substrait_Named_Struct_t_struct__MSGTYPE substrait_Type_Struct_t

extern const pb_msgdesc_t substrait_Type_t_msg;
extern const pb_msgdesc_t substrait_Type_Boolean_t_msg;
extern const pb_msgdesc_t substrait_Type_I8_t_msg;
extern const pb_msgdesc_t substrait_Type_I16_t_msg;
extern const pb_msgdesc_t substrait_Type_I32_t_msg;
extern const pb_msgdesc_t substrait_Type_I64_t_msg;
extern const pb_msgdesc_t substrait_Type_FP32_t_msg;
extern const pb_msgdesc_t substrait_Type_FP64_t_msg;
extern const pb_msgdesc_t substrait_Type_String_t_msg;
extern const pb_msgdesc_t substrait_Type_Binary_t_msg;
extern const pb_msgdesc_t substrait_Type_Timestamp_t_msg;
extern const pb_msgdesc_t substrait_Type_Date_t_msg;
extern const pb_msgdesc_t substrait_Type_Time_t_msg;
extern const pb_msgdesc_t substrait_Type_Timestamp_TZ_t_msg;
extern const pb_msgdesc_t substrait_Type_Interval_Year_t_msg;
extern const pb_msgdesc_t substrait_Type_Interval_Day_t_msg;
extern const pb_msgdesc_t substrait_Type_Interval_Compound_t_msg;
extern const pb_msgdesc_t substrait_Type_UUID_t_msg;
extern const pb_msgdesc_t substrait_Type_Fixed_Char_t_msg;
extern const pb_msgdesc_t substrait_Type_Var_Char_t_msg;
extern const pb_msgdesc_t substrait_Type_Fixed_Binary_t_msg;
extern const pb_msgdesc_t substrait_Type_Decimal_t_msg;
extern const pb_msgdesc_t substrait_Type_Precision_Timestamp_t_msg;
extern const pb_msgdesc_t substrait_Type_Precision_Timestamp_TZ_t_msg;
extern const pb_msgdesc_t substrait_Type_Struct_t_msg;
extern const pb_msgdesc_t substrait_Type_List_t_msg;
extern const pb_msgdesc_t substrait_Type_Map_t_msg;
extern const pb_msgdesc_t substrait_Type_User_Defined_t_msg;
extern const pb_msgdesc_t substrait_Type_Parameter_t_msg;
extern const pb_msgdesc_t substrait_Named_Struct_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_TYPE_FIELDS &substrait_Type_t_msg
#define SUBSTRAIT_TYPE_BOOLEAN_FIELDS &substrait_Type_Boolean_t_msg
#define SUBSTRAIT_TYPE_I8_FIELDS &substrait_Type_I8_t_msg
#define SUBSTRAIT_TYPE_I16_FIELDS &substrait_Type_I16_t_msg
#define SUBSTRAIT_TYPE_I32_FIELDS &substrait_Type_I32_t_msg
#define SUBSTRAIT_TYPE_I64_FIELDS &substrait_Type_I64_t_msg
#define SUBSTRAIT_TYPE_FP32_FIELDS &substrait_Type_FP32_t_msg
#define SUBSTRAIT_TYPE_FP64_FIELDS &substrait_Type_FP64_t_msg
#define SUBSTRAIT_TYPE_STRING_FIELDS &substrait_Type_String_t_msg
#define SUBSTRAIT_TYPE_BINARY_FIELDS &substrait_Type_Binary_t_msg
#define SUBSTRAIT_TYPE_TIMESTAMP_FIELDS &substrait_Type_Timestamp_t_msg
#define SUBSTRAIT_TYPE_DATE_FIELDS &substrait_Type_Date_t_msg
#define SUBSTRAIT_TYPE_TIME_FIELDS &substrait_Type_Time_t_msg
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_FIELDS &substrait_Type_Timestamp_TZ_t_msg
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_FIELDS &substrait_Type_Interval_Year_t_msg
#define SUBSTRAIT_TYPE_INTERVAL_DAY_FIELDS &substrait_Type_Interval_Day_t_msg
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_FIELDS &substrait_Type_Interval_Compound_t_msg
#define SUBSTRAIT_TYPE_UUID_FIELDS &substrait_Type_UUID_t_msg
#define SUBSTRAIT_TYPE_FIXED_CHAR_FIELDS &substrait_Type_Fixed_Char_t_msg
#define SUBSTRAIT_TYPE_VAR_CHAR_FIELDS &substrait_Type_Var_Char_t_msg
#define SUBSTRAIT_TYPE_FIXED_BINARY_FIELDS &substrait_Type_Fixed_Binary_t_msg
#define SUBSTRAIT_TYPE_DECIMAL_FIELDS &substrait_Type_Decimal_t_msg
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_FIELDS &substrait_Type_Precision_Timestamp_t_msg
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_FIELDS &substrait_Type_Precision_Timestamp_TZ_t_msg
#define SUBSTRAIT_TYPE_STRUCT_FIELDS &substrait_Type_Struct_t_msg
#define SUBSTRAIT_TYPE_LIST_FIELDS &substrait_Type_List_t_msg
#define SUBSTRAIT_TYPE_MAP_FIELDS &substrait_Type_Map_t_msg
#define SUBSTRAIT_TYPE_USER_DEFINED_FIELDS &substrait_Type_User_Defined_t_msg
#define SUBSTRAIT_TYPE_PARAMETER_FIELDS &substrait_Type_Parameter_t_msg
#define SUBSTRAIT_NAMED_STRUCT_FIELDS &substrait_Named_Struct_t_msg

/* Maximum encoded size of messages (where known) */
/* substrait_Type_size depends on runtime parameters */
/* substrait_Type_Struct_size depends on runtime parameters */
/* substrait_Type_List_size depends on runtime parameters */
/* substrait_Type_Map_size depends on runtime parameters */
/* substrait_Type_UserDefined_size depends on runtime parameters */
/* substrait_Type_Parameter_size depends on runtime parameters */
/* substrait_NamedStruct_size depends on runtime parameters */
#define SUBSTRAIT_SUBSTRAIT_TYPE_PB_H_MAX_SIZE   SUBSTRAIT_TYPE_DECIMAL_SIZE
#define SUBSTRAIT_TYPE_BINARY_SIZE               8
#define SUBSTRAIT_TYPE_BOOLEAN_SIZE              8
#define SUBSTRAIT_TYPE_DATE_SIZE                 8
#define SUBSTRAIT_TYPE_DECIMAL_SIZE              30
#define SUBSTRAIT_TYPE_FIXED_BINARY_SIZE         19
#define SUBSTRAIT_TYPE_FIXED_CHAR_SIZE           19
#define SUBSTRAIT_TYPE_FP32_SIZE                 8
#define SUBSTRAIT_TYPE_FP64_SIZE                 8
#define SUBSTRAIT_TYPE_I16_SIZE                  8
#define SUBSTRAIT_TYPE_I32_SIZE                  8
#define SUBSTRAIT_TYPE_I64_SIZE                  8
#define SUBSTRAIT_TYPE_I8_SIZE                   8
#define SUBSTRAIT_TYPE_INTERVAL_COMPOUND_SIZE    19
#define SUBSTRAIT_TYPE_INTERVAL_DAY_SIZE         19
#define SUBSTRAIT_TYPE_INTERVAL_YEAR_SIZE        8
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_SIZE  19
#define SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ_SIZE 19
#define SUBSTRAIT_TYPE_STRING_SIZE               8
#define SUBSTRAIT_TYPE_TIMESTAMP_SIZE            8
#define SUBSTRAIT_TYPE_TIMESTAMP_TZ_SIZE         8
#define SUBSTRAIT_TYPE_TIME_SIZE                 8
#define SUBSTRAIT_TYPE_UUID_SIZE                 8
#define SUBSTRAIT_TYPE_VAR_CHAR_SIZE             19

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
