/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_TYPE_EXPRESSIONS_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_TYPE_EXPRESSIONS_PB_H_INCLUDED
#include <pb.h>
#include "substrait/type.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum substrait_Derivation_Expression_Unary_Op_Unary_Op_Type {
    SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_UNARY_OP_TYPE_UNSPECIFIED = 0,
    SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_UNARY_OP_TYPE_BOOLEAN_NOT = 1
} substrait_Derivation_Expression_Unary_Op_Unary_Op_Type_t;

typedef enum substrait_Derivation_Expression_Binary_Op_Binary_Op_Type {
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_UNSPECIFIED = 0,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_PLUS = 1,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_MINUS = 2,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_MULTIPLY = 3,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_DIVIDE = 4,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_MIN = 5,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_MAX = 6,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_GREATER_THAN = 7,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_LESS_THAN = 8,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_AND = 9,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_OR = 10,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_EQUALS = 11,
    SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_COVERS = 12
} substrait_Derivation_Expression_Binary_Op_Binary_Op_Type_t;

/* Struct definitions */
typedef struct substrait_Derivation_Expression_Expression_Fixed_Char {
    pb_callback_t length;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Fixed_Char_t;

typedef struct substrait_Derivation_Expression_Expression_Var_Char {
    pb_callback_t length;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Var_Char_t;

typedef struct substrait_Derivation_Expression_Expression_Fixed_Binary {
    pb_callback_t length;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Fixed_Binary_t;

typedef struct substrait_Derivation_Expression_Expression_Decimal {
    pb_callback_t scale;
    pb_callback_t precision;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Decimal_t;

typedef struct substrait_Derivation_Expression_Expression_Precision_Timestamp {
    pb_callback_t precision;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Precision_Timestamp_t;

typedef struct substrait_Derivation_Expression_Expression_Interval_Day {
    pb_callback_t precision;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Interval_Day_t;

typedef struct substrait_Derivation_Expression_Expression_Interval_Compound {
    pb_callback_t precision;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Interval_Compound_t;

typedef struct substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ {
    pb_callback_t precision;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ_t;

typedef struct substrait_Derivation_Expression_Expression_Struct {
    pb_callback_t types;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Derivation_Expression_Expression_Struct_t;

typedef struct substrait_Derivation_Expression_Expression_Named_Struct {
    pb_callback_t names;
    bool has_struct_;
    substrait_Derivation_Expression_Expression_Struct_t struct_;
} substrait_Derivation_Expression_Expression_Named_Struct_t;

typedef struct substrait_Derivation_Expression_Expression_List {
    pb_callback_t type;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_List_t;

typedef struct substrait_Derivation_Expression_Expression_Map {
    pb_callback_t key;
    pb_callback_t value;
    pb_callback_t variation_pointer;
    pb_callback_t nullability;
} substrait_Derivation_Expression_Expression_Map_t;

typedef struct substrait_Derivation_Expression_Expression_User_Defined {
    uint32_t type_pointer;
    uint32_t variation_pointer;
    substrait_Type_Nullability_t nullability;
} substrait_Derivation_Expression_Expression_User_Defined_t;

typedef struct substrait_Derivation_Expression_If_Else {
    pb_callback_t if_condition;
    pb_callback_t if_return;
    pb_callback_t else_return;
} substrait_Derivation_Expression_If_Else_t;

typedef struct substrait_Derivation_Expression_Unary_Op {
    pb_callback_t op_type;
    pb_callback_t arg;
} substrait_Derivation_Expression_Unary_Op_t;

typedef struct substrait_Derivation_Expression_Binary_Op {
    pb_callback_t op_type;
    pb_callback_t arg1;
    pb_callback_t arg2;
} substrait_Derivation_Expression_Binary_Op_t;

typedef struct substrait_Derivation_Expression_Return_Program {
    pb_callback_t assignments;
    pb_callback_t final_expression;
} substrait_Derivation_Expression_Return_Program_t;

typedef struct substrait_Derivation_Expression {
    pb_size_t which_kind;
    union substrait_Derivation_Expression_kind {
        substrait_Type_Boolean_t bool_;
        substrait_Type_I8_t i8;
        substrait_Type_I16_t i16;
        substrait_Type_I32_t i32;
        substrait_Type_I64_t i64;
        substrait_Type_FP32_t fp32;
        substrait_Type_FP64_t fp64;
        substrait_Type_String_t string;
        substrait_Type_Binary_t binary;
        /* Deprecated in favor of `ExpressionPrecisionTimestamp precision_timestamp` */
        substrait_Type_Timestamp_t timestamp;
        substrait_Type_Date_t date;
        substrait_Type_Time_t time;
        substrait_Type_Interval_Year_t interval_year;
        substrait_Derivation_Expression_Expression_Interval_Day_t interval_day;
        substrait_Derivation_Expression_Expression_Fixed_Char_t fixed_char;
        substrait_Derivation_Expression_Expression_Var_Char_t varchar;
        substrait_Derivation_Expression_Expression_Fixed_Binary_t fixed_binary;
        substrait_Derivation_Expression_Expression_Decimal_t decimal;
        substrait_Derivation_Expression_Expression_Struct_t struct_;
        substrait_Derivation_Expression_Expression_List_t list;
        substrait_Derivation_Expression_Expression_Map_t map;
        /* Deprecated in favor of `ExpressionPrecisionTimestampTZ precision_timestamp_tz` */
        substrait_Type_Timestamp_TZ_t timestamp_tz;
        substrait_Derivation_Expression_Expression_User_Defined_t user_defined;
        /* Deprecated in favor of user_defined, which allows nullability and
     variations to be specified. If user_defined_pointer is encountered,
     treat it as being non-nullable and having the default variation. */
        uint32_t user_defined_pointer;
        substrait_Type_UUID_t uuid;
        pb_callback_t type_parameter_name;
        pb_callback_t integer_parameter_name;
        int32_t integer_literal;
        substrait_Derivation_Expression_Unary_Op_t unary_op;
        substrait_Derivation_Expression_Binary_Op_t binary_op;
        substrait_Derivation_Expression_If_Else_t if_else;
        substrait_Derivation_Expression_Return_Program_t return_program;
        substrait_Derivation_Expression_Expression_Precision_Timestamp_t precision_timestamp;
        substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ_t precision_timestamp_tz;
        substrait_Derivation_Expression_Expression_Interval_Compound_t interval_compound;
    } kind;
} substrait_Derivation_Expression_t;

typedef struct substrait_Derivation_Expression_Return_Program_Assignment {
    pb_callback_t name;
    bool has_expression;
    substrait_Derivation_Expression_t expression;
} substrait_Derivation_Expression_Return_Program_Assignment_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_MIN SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_UNARY_OP_TYPE_UNSPECIFIED
#define _SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_MAX SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_UNARY_OP_TYPE_BOOLEAN_NOT
#define _SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_ARRAYSIZE ((substrait_Derivation_Expression_Unary_Op_Unary_Op_Type_t)(SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_UNARY_OP_TYPE_UNARY_OP_TYPE_BOOLEAN_NOT+1))

#define _SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_MIN SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_UNSPECIFIED
#define _SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_MAX SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_COVERS
#define _SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_ARRAYSIZE ((substrait_Derivation_Expression_Binary_Op_Binary_Op_Type_t)(SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_BINARY_OP_TYPE_BINARY_OP_TYPE_COVERS+1))


#define substrait_Derivation_Expression_Expression_Fixed_Char_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Var_Char_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Fixed_Binary_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Decimal_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Precision_Timestamp_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Interval_Day_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Interval_Compound_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Struct_t_nullability_ENUMTYPE substrait_Type_Nullability_t


#define substrait_Derivation_Expression_Expression_List_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_Map_t_nullability_ENUMTYPE substrait_Type_Nullability_t

#define substrait_Derivation_Expression_Expression_User_Defined_t_nullability_ENUMTYPE substrait_Type_Nullability_t


#define substrait_Derivation_Expression_Unary_Op_t_op_type_ENUMTYPE substrait_Derivation_Expression_Unary_Op_Unary_Op_Type_t

#define substrait_Derivation_Expression_Binary_Op_t_op_type_ENUMTYPE substrait_Derivation_Expression_Binary_Op_Binary_Op_Type_t




/* Initializer values for message structs */
#define SUBSTRAIT_DERIVATION_EXPRESSION_INIT_DEFAULT {0, {SUBSTRAIT_TYPE_BOOLEAN_INIT_DEFAULT}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_INIT_DEFAULT {{{NULL}, NULL}, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_INIT_DEFAULT {{{NULL}, NULL}, false, SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_INIT_DEFAULT}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_INIT_DEFAULT {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_INIT_DEFAULT {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_INIT_DEFAULT {{{NULL}, NULL}, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_DEFAULT}
#define SUBSTRAIT_DERIVATION_EXPRESSION_INIT_ZERO {0, {SUBSTRAIT_TYPE_BOOLEAN_INIT_ZERO}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_INIT_ZERO {{{NULL}, NULL}, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_INIT_ZERO {{{NULL}, NULL}, false, SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_INIT_ZERO}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_INIT_ZERO {0, 0, _SUBSTRAIT_TYPE_NULLABILITY_MIN}
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_INIT_ZERO {{{NULL}, NULL}, {{NULL}, NULL}}
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_INIT_ZERO {{{NULL}, NULL}, false, SUBSTRAIT_DERIVATION_EXPRESSION_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_LENGTH_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_LENGTH_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_LENGTH_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_SCALE_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_PRECISION_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_VARIATION_POINTER_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_NULLABILITY_TAG 4
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_PRECISION_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_PRECISION_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_PRECISION_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_PRECISION_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_TYPES_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_NAMES_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_STRUCT_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_TYPE_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_KEY_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_VALUE_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_VARIATION_POINTER_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_NULLABILITY_TAG 4
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_TYPE_POINTER_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_VARIATION_POINTER_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_NULLABILITY_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_IF_CONDITION_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_IF_RETURN_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_ELSE_RETURN_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_OP_TYPE_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_ARG_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_OP_TYPE_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_ARG1_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_ARG2_TAG 3
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENTS_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_FINAL_EXPRESSION_TAG 2
#define SUBSTRAIT_DERIVATION_EXPRESSION_BOOL_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_I8_TAG   2
#define SUBSTRAIT_DERIVATION_EXPRESSION_I16_TAG  3
#define SUBSTRAIT_DERIVATION_EXPRESSION_I32_TAG  5
#define SUBSTRAIT_DERIVATION_EXPRESSION_I64_TAG  7
#define SUBSTRAIT_DERIVATION_EXPRESSION_FP32_TAG 10
#define SUBSTRAIT_DERIVATION_EXPRESSION_FP64_TAG 11
#define SUBSTRAIT_DERIVATION_EXPRESSION_STRING_TAG 12
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_TAG 13
#define SUBSTRAIT_DERIVATION_EXPRESSION_TIMESTAMP_TAG 14
#define SUBSTRAIT_DERIVATION_EXPRESSION_DATE_TAG 16
#define SUBSTRAIT_DERIVATION_EXPRESSION_TIME_TAG 17
#define SUBSTRAIT_DERIVATION_EXPRESSION_INTERVAL_YEAR_TAG 19
#define SUBSTRAIT_DERIVATION_EXPRESSION_INTERVAL_DAY_TAG 20
#define SUBSTRAIT_DERIVATION_EXPRESSION_FIXED_CHAR_TAG 21
#define SUBSTRAIT_DERIVATION_EXPRESSION_VARCHAR_TAG 22
#define SUBSTRAIT_DERIVATION_EXPRESSION_FIXED_BINARY_TAG 23
#define SUBSTRAIT_DERIVATION_EXPRESSION_DECIMAL_TAG 24
#define SUBSTRAIT_DERIVATION_EXPRESSION_STRUCT_TAG 25
#define SUBSTRAIT_DERIVATION_EXPRESSION_LIST_TAG 27
#define SUBSTRAIT_DERIVATION_EXPRESSION_MAP_TAG  28
#define SUBSTRAIT_DERIVATION_EXPRESSION_TIMESTAMP_TZ_TAG 29
#define SUBSTRAIT_DERIVATION_EXPRESSION_USER_DEFINED_TAG 30
#define SUBSTRAIT_DERIVATION_EXPRESSION_USER_DEFINED_POINTER_TAG 31
#define SUBSTRAIT_DERIVATION_EXPRESSION_UUID_TAG 32
#define SUBSTRAIT_DERIVATION_EXPRESSION_TYPE_PARAMETER_NAME_TAG 33
#define SUBSTRAIT_DERIVATION_EXPRESSION_INTEGER_PARAMETER_NAME_TAG 34
#define SUBSTRAIT_DERIVATION_EXPRESSION_INTEGER_LITERAL_TAG 35
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_TAG 36
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_TAG 37
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_TAG 38
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_TAG 39
#define SUBSTRAIT_DERIVATION_EXPRESSION_PRECISION_TIMESTAMP_TAG 40
#define SUBSTRAIT_DERIVATION_EXPRESSION_PRECISION_TIMESTAMP_TZ_TAG 41
#define SUBSTRAIT_DERIVATION_EXPRESSION_INTERVAL_COMPOUND_TAG 42
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_NAME_TAG 1
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_EXPRESSION_TAG 2

/* Struct field encoding specification for nanopb */
#define SUBSTRAIT_DERIVATION_EXPRESSION_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,bool_,kind.bool_),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i8,kind.i8),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i16,kind.i16),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i32,kind.i32),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,i64,kind.i64),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fp32,kind.fp32),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fp64,kind.fp64),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,string,kind.string),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,binary,kind.binary),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,timestamp,kind.timestamp),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,date,kind.date),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,time,kind.time),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_year,kind.interval_year),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_day,kind.interval_day),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fixed_char,kind.fixed_char),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,varchar,kind.varchar),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,fixed_binary,kind.fixed_binary),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,decimal,kind.decimal),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,struct_,kind.struct_),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,list,kind.list),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,map,kind.map),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,timestamp_tz,kind.timestamp_tz),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,user_defined,kind.user_defined),  30) \
X(a, STATIC,   ONEOF,    UINT32,   (kind,user_defined_pointer,kind.user_defined_pointer),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,uuid,kind.uuid),  32) \
X(a, CALLBACK, ONEOF,    STRING,   (kind,type_parameter_name,kind.type_parameter_name),  33) \
X(a, CALLBACK, ONEOF,    STRING,   (kind,integer_parameter_name,kind.integer_parameter_name),  34) \
X(a, STATIC,   ONEOF,    INT32,    (kind,integer_literal,kind.integer_literal),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,unary_op,kind.unary_op),  36) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,binary_op,kind.binary_op),  37) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,if_else,kind.if_else),  38) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,return_program,kind.return_program),  39) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,precision_timestamp,kind.precision_timestamp),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,precision_timestamp_tz,kind.precision_timestamp_tz),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,interval_compound,kind.interval_compound),  42)
#define SUBSTRAIT_DERIVATION_EXPRESSION_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_DEFAULT NULL
#define substrait_Derivation_Expression_t_kind_bool__MSGTYPE substrait_Type_Boolean_t
#define substrait_Derivation_Expression_t_kind_i8_MSGTYPE substrait_Type_I8_t
#define substrait_Derivation_Expression_t_kind_i16_MSGTYPE substrait_Type_I16_t
#define substrait_Derivation_Expression_t_kind_i32_MSGTYPE substrait_Type_I32_t
#define substrait_Derivation_Expression_t_kind_i64_MSGTYPE substrait_Type_I64_t
#define substrait_Derivation_Expression_t_kind_fp32_MSGTYPE substrait_Type_FP32_t
#define substrait_Derivation_Expression_t_kind_fp64_MSGTYPE substrait_Type_FP64_t
#define substrait_Derivation_Expression_t_kind_string_MSGTYPE substrait_Type_String_t
#define substrait_Derivation_Expression_t_kind_binary_MSGTYPE substrait_Type_Binary_t
#define substrait_Derivation_Expression_t_kind_timestamp_MSGTYPE substrait_Type_Timestamp_t
#define substrait_Derivation_Expression_t_kind_date_MSGTYPE substrait_Type_Date_t
#define substrait_Derivation_Expression_t_kind_time_MSGTYPE substrait_Type_Time_t
#define substrait_Derivation_Expression_t_kind_interval_year_MSGTYPE substrait_Type_Interval_Year_t
#define substrait_Derivation_Expression_t_kind_interval_day_MSGTYPE substrait_Derivation_Expression_Expression_Interval_Day_t
#define substrait_Derivation_Expression_t_kind_fixed_char_MSGTYPE substrait_Derivation_Expression_Expression_Fixed_Char_t
#define substrait_Derivation_Expression_t_kind_varchar_MSGTYPE substrait_Derivation_Expression_Expression_Var_Char_t
#define substrait_Derivation_Expression_t_kind_fixed_binary_MSGTYPE substrait_Derivation_Expression_Expression_Fixed_Binary_t
#define substrait_Derivation_Expression_t_kind_decimal_MSGTYPE substrait_Derivation_Expression_Expression_Decimal_t
#define substrait_Derivation_Expression_t_kind_struct__MSGTYPE substrait_Derivation_Expression_Expression_Struct_t
#define substrait_Derivation_Expression_t_kind_list_MSGTYPE substrait_Derivation_Expression_Expression_List_t
#define substrait_Derivation_Expression_t_kind_map_MSGTYPE substrait_Derivation_Expression_Expression_Map_t
#define substrait_Derivation_Expression_t_kind_timestamp_tz_MSGTYPE substrait_Type_Timestamp_TZ_t
#define substrait_Derivation_Expression_t_kind_user_defined_MSGTYPE substrait_Derivation_Expression_Expression_User_Defined_t
#define substrait_Derivation_Expression_t_kind_uuid_MSGTYPE substrait_Type_UUID_t
#define substrait_Derivation_Expression_t_kind_unary_op_MSGTYPE substrait_Derivation_Expression_Unary_Op_t
#define substrait_Derivation_Expression_t_kind_binary_op_MSGTYPE substrait_Derivation_Expression_Binary_Op_t
#define substrait_Derivation_Expression_t_kind_if_else_MSGTYPE substrait_Derivation_Expression_If_Else_t
#define substrait_Derivation_Expression_t_kind_return_program_MSGTYPE substrait_Derivation_Expression_Return_Program_t
#define substrait_Derivation_Expression_t_kind_precision_timestamp_MSGTYPE substrait_Derivation_Expression_Expression_Precision_Timestamp_t
#define substrait_Derivation_Expression_t_kind_precision_timestamp_tz_MSGTYPE substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ_t
#define substrait_Derivation_Expression_t_kind_interval_compound_MSGTYPE substrait_Derivation_Expression_Expression_Interval_Compound_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  length,            1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Fixed_Char_t_length_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  length,            1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Var_Char_t_length_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  length,            1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Fixed_Binary_t_length_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  scale,             1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  precision,         2) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   3) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       4)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Decimal_t_scale_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Derivation_Expression_Expression_Decimal_t_precision_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  precision,         1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Precision_Timestamp_t_precision_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  precision,         1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Interval_Day_t_precision_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  precision,         1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Interval_Compound_t_precision_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  precision,         1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ_t_precision_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  types,             1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Struct_t_types_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   names,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  struct_,           2)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Named_Struct_t_struct__MSGTYPE substrait_Derivation_Expression_Expression_Struct_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  type,              1) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_List_t_type_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  key,               1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  value,             2) \
X(a, CALLBACK, SINGULAR, UINT32,   variation_pointer,   3) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       4)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_DEFAULT NULL
#define substrait_Derivation_Expression_Expression_Map_t_key_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Derivation_Expression_Expression_Map_t_value_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type_pointer,      1) \
X(a, STATIC,   SINGULAR, UINT32,   variation_pointer,   2) \
X(a, STATIC,   SINGULAR, UENUM,    nullability,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_CALLBACK NULL
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_DEFAULT NULL

#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  if_condition,      1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  if_return,         2) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  else_return,       3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_DEFAULT NULL
#define substrait_Derivation_Expression_If_Else_t_if_condition_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Derivation_Expression_If_Else_t_if_return_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Derivation_Expression_If_Else_t_else_return_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UENUM,    op_type,           1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  arg,               2)
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_DEFAULT NULL
#define substrait_Derivation_Expression_Unary_Op_t_arg_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UENUM,    op_type,           1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  arg1,              2) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  arg2,              3)
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_DEFAULT NULL
#define substrait_Derivation_Expression_Binary_Op_t_arg1_MSGTYPE substrait_Derivation_Expression_t
#define substrait_Derivation_Expression_Binary_Op_t_arg2_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  assignments,       1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  final_expression,   2)
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_DEFAULT NULL
#define substrait_Derivation_Expression_Return_Program_t_assignments_MSGTYPE substrait_Derivation_Expression_Return_Program_Assignment_t
#define substrait_Derivation_Expression_Return_Program_t_final_expression_MSGTYPE substrait_Derivation_Expression_t

#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  expression,        2)
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_CALLBACK pb_default_field_callback
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_DEFAULT NULL
#define substrait_Derivation_Expression_Return_Program_Assignment_t_expression_MSGTYPE substrait_Derivation_Expression_t

extern const pb_msgdesc_t substrait_Derivation_Expression_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Fixed_Char_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Var_Char_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Fixed_Binary_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Decimal_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Precision_Timestamp_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Interval_Day_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Interval_Compound_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Struct_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Named_Struct_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_List_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_Map_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Expression_User_Defined_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_If_Else_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Unary_Op_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Binary_Op_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Return_Program_t_msg;
extern const pb_msgdesc_t substrait_Derivation_Expression_Return_Program_Assignment_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SUBSTRAIT_DERIVATION_EXPRESSION_FIELDS &substrait_Derivation_Expression_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_CHAR_FIELDS &substrait_Derivation_Expression_Expression_Fixed_Char_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_VAR_CHAR_FIELDS &substrait_Derivation_Expression_Expression_Var_Char_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_FIXED_BINARY_FIELDS &substrait_Derivation_Expression_Expression_Fixed_Binary_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_DECIMAL_FIELDS &substrait_Derivation_Expression_Expression_Decimal_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_FIELDS &substrait_Derivation_Expression_Expression_Precision_Timestamp_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_DAY_FIELDS &substrait_Derivation_Expression_Expression_Interval_Day_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_INTERVAL_COMPOUND_FIELDS &substrait_Derivation_Expression_Expression_Interval_Compound_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_PRECISION_TIMESTAMP_TZ_FIELDS &substrait_Derivation_Expression_Expression_Precision_Timestamp_TZ_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_STRUCT_FIELDS &substrait_Derivation_Expression_Expression_Struct_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_NAMED_STRUCT_FIELDS &substrait_Derivation_Expression_Expression_Named_Struct_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_LIST_FIELDS &substrait_Derivation_Expression_Expression_List_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_MAP_FIELDS &substrait_Derivation_Expression_Expression_Map_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_FIELDS &substrait_Derivation_Expression_Expression_User_Defined_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_IF_ELSE_FIELDS &substrait_Derivation_Expression_If_Else_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_UNARY_OP_FIELDS &substrait_Derivation_Expression_Unary_Op_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_BINARY_OP_FIELDS &substrait_Derivation_Expression_Binary_Op_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_FIELDS &substrait_Derivation_Expression_Return_Program_t_msg
#define SUBSTRAIT_DERIVATION_EXPRESSION_RETURN_PROGRAM_ASSIGNMENT_FIELDS &substrait_Derivation_Expression_Return_Program_Assignment_t_msg

/* Maximum encoded size of messages (where known) */
/* substrait_DerivationExpression_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionFixedChar_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionVarChar_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionFixedBinary_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionDecimal_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionPrecisionTimestamp_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionIntervalDay_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionIntervalCompound_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionPrecisionTimestampTZ_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionStruct_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionNamedStruct_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionList_size depends on runtime parameters */
/* substrait_DerivationExpression_ExpressionMap_size depends on runtime parameters */
/* substrait_DerivationExpression_IfElse_size depends on runtime parameters */
/* substrait_DerivationExpression_UnaryOp_size depends on runtime parameters */
/* substrait_DerivationExpression_BinaryOp_size depends on runtime parameters */
/* substrait_DerivationExpression_ReturnProgram_size depends on runtime parameters */
/* substrait_DerivationExpression_ReturnProgram_Assignment_size depends on runtime parameters */
#define SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_SIZE 14
#define SUBSTRAIT_SUBSTRAIT_TYPE_EXPRESSIONS_PB_H_MAX_SIZE SUBSTRAIT_DERIVATION_EXPRESSION_EXPRESSION_USER_DEFINED_SIZE

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
