/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "substrait/type.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SUBSTRAIT_TYPE, substrait_Type_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_BOOLEAN, substrait_Type_Boolean_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_I8, substrait_Type_I8_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_I16, substrait_Type_I16_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_I32, substrait_Type_I32_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_I64, substrait_Type_I64_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_FP32, substrait_Type_FP32_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_FP64, substrait_Type_FP64_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_STRING, substrait_Type_String_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_BINARY, substrait_Type_Binary_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_TIMESTAMP, substrait_Type_Timestamp_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_DATE, substrait_Type_Date_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_TIME, substrait_Type_Time_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_TIMESTAMP_TZ, substrait_Type_Timestamp_TZ_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_INTERVAL_YEAR, substrait_Type_Interval_Year_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_INTERVAL_DAY, substrait_Type_Interval_Day_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_INTERVAL_COMPOUND, substrait_Type_Interval_Compound_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_UUID, substrait_Type_UUID_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_FIXED_CHAR, substrait_Type_Fixed_Char_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_VAR_CHAR, substrait_Type_Var_Char_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_FIXED_BINARY, substrait_Type_Fixed_Binary_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_DECIMAL, substrait_Type_Decimal_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_PRECISION_TIMESTAMP, substrait_Type_Precision_Timestamp_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_PRECISION_TIMESTAMP_TZ, substrait_Type_Precision_Timestamp_TZ_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_STRUCT, substrait_Type_Struct_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_LIST, substrait_Type_List_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_MAP, substrait_Type_Map_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_USER_DEFINED, substrait_Type_User_Defined_t, AUTO)


PB_BIND(SUBSTRAIT_TYPE_PARAMETER, substrait_Type_Parameter_t, AUTO)


PB_BIND(SUBSTRAIT_NAMED_STRUCT, substrait_Named_Struct_t, AUTO)





